### ISSUE TITLE
"SetupTransparentProxy()" appears in local VPN filtering mode

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1001]
Android 4.4.2
Adguard 2.8.76

[debug (6).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/674338/debug.6.txt.zip)

```

16:51:51.425 [pool-2-thread-199] INFO  com.adguard.android.e.c - Setting up transparent proxy.
16:51:53.760 [pool-2-thread-199] ERROR com.adguard.android.e.c - Installing proxy configuration failed

java.io.IOException: setupTransparentProxy: Root access has not been given.
    at com.adguard.android.e.c.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.e.a.e(Unknown Source) ~[na:0.0]
    at com.adguard.android.e.a.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.e.a$1.a(Unknown Source) ~[na:0.0]
    at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
16:51:53.762 [pool-2-thread-199] ERROR com.adguard.android.e.a - Error applying proxy settings
java.io.IOException: Installing proxy configuration failed
    at com.adguard.android.e.a.e(Unknown Source) ~[na:0.0]
    at com.adguard.android.e.a.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.e.a$1.a(Unknown Source) ~[na:0.0]
    at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
16:51:53.763 [pool-2-thread-199] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: PROXY_CONFIG_ERROR
16:51:53.792 [pool-2-thread-199] INFO  com.adguard.android.service.ao - Updating widgets for PROXY_CONFIG_ERROR protection

```

**Comment by ameshkov** [comment]
I suppose this is a user's mistake and actually he changed the filtering mode to proxy.
Let's doublecheck it, though.

**Comment by Yana-SUP** [comment]
Here are the new logs. The user says that he uses VPN.
[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/697119/debug.1.txt)

User ID: 1469472

**Comment by zebrum** [comment]
@ameshkov the same thing in logs

**Comment by ameshkov** [comment]
What I see in the log file is possible only in the case of having "Proxy" filtering mode.
There is literally no other option.

Ask user to clear app data in order for settings to be reset to default.
