### ISSUE TITLE
Cannot parse basic filter rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1009]
```
Invalid filter rule: @@||$xmlhttprequest,domain=last.fm

java.lang.StringIndexOutOfBoundsException: length=2; regionStart=2; regionLength=-1
	at java.lang.String.substring(String.java:1931) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.v(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.f(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.o.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.n.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.y.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.y.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ad.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.s.a(Unknown Source) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Review:
adguard-java-code/review/AJC-CR-158
