### ISSUE TITLE
Clearing YT data causes timeout exception

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1012]
To reproduce this issue you should enable `pref.root.clear.youtube`.

The problem is that (according to the log) other threads are stuck in waiting until this command finishes its work.

```
03:50:42.879 [main] INFO  c.a.android.receivers.BaseReceiver - Finished VPN auto restart check
03:50:42.880 [main] INFO  c.a.a.r.NetworkStateReceiver - Current active network info: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "ASUS_5G", failover: false, available: true, roaming: false, metered: false]
03:51:02.478 [pool-2-thread-1] WARN  com.adguard.android.service.b - Error while clearing YT data: 
java.util.concurrent.TimeoutException: 
	at com.stericson.RootTools.b.f.<init>(Unknown Source) ~[na:0.0]
	at com.stericson.RootTools.b.f.c(Unknown Source) ~[na:0.0]
	at com.stericson.RootTools.b.f.c(Unknown Source) ~[na:0.0]
	at com.adguard.android.commons.h.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.b.e(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.b$1.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
03:51:02.485 [main] INFO  c.a.a.r.NetworkStateReceiver - Network WIFI connected. State=CONNECTED.
03:51:02.490 [main] INFO  c.a.android.filtering.filter.e - Connected to network type=1
03:51:02.497 [main] INFO  com.adguard.android.ServiceManager - Creating ServiceManager
```

**Comment by nkartyshov** [comment]
Problem with given root access. User didn't accepts root access, so an app throws timeout exception.

**Comment by ameshkov** [comment]
I know. The problem is not in the timeout, but that the other threads are might be stuck in waiting.

Check that there's no excessive locking.

**Comment by nkartyshov** [comment]
I have not found a lock for UI threads, but log contains RootDeniedException if app didn't has root access.
