### ISSUE TITLE
Error while parsing filter rule: Unknown pseudo class

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#1020]
```
12:25:57.244 [pool-2-thread-1] WARN  com.adguard.filter.rules.FilterRule - Error creating filter rule sports.ru###branding-layout > div.pageLayout > noindex:first-child`:

java.lang.IllegalArgumentException: Unknown pseudo class: #branding-layout > div.pageLayout > noindex:first-child`
	at com.adguard.filter.rules.CssFilterRule.<init>(CssFilterRule.java:134) ~[na:0.0]
	at com.adguard.filter.rules.FilterRule.createRule(FilterRule.java:104) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRule(RequestFilter.java:84) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRules(RequestFilter.java:100) ~[na:0.0]
	at com.adguard.android.filtering.filter.HttpFilter.initialize(HttpFilter.java:118) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.initializeHttpFilter(ProtectionServiceImpl.java:286) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.configureHttpFilter(ProtectionServiceImpl.java:303) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.access$400(ProtectionServiceImpl.java:35) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl$StartVpnServiceTask.processTask(ProtectionServiceImpl.java:320) ~[na:0.0]
	at com.adguard.android.service.LongRunningTask.execute(LongRunningTask.java:46) ~[na:0.0]
	at com.adguard.commons.concurrent.DispatcherThreadPool$DispatcherTaskRunner.run(DispatcherThreadPool.java:206) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by nkartyshov** [comment]
I cannot reproduce. Maybe, this problem was in oldest version app, but I added test for this rules.
