### ISSUE TITLE
Unnecessary HTTPS exception added

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1042]
```
14:42:24.048 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.a - TCP id=156120 Server has accepted new tcp connection. Connection info=com.yandex.browser.alpha /172.16.209.1:41012 /37.209.240.1:443 10149
14:42:24.097 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/127.0.0.1:37393 Read 205 bytes from socket channel
14:42:24.099 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.a - TCP id=156120 Accepting incoming SSL connection
14:42:24.100 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Received ClientHello:
14:42:24.101 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Creating new remote endpoint
14:42:24.142 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=156120 Client provided unsupported cipher: 0xdada, ignoring
14:42:24.142 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=156120 Client provided unsupported cipher: 0xcca9, ignoring
14:42:24.142 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=156120 Client provided unsupported cipher: 0xcca8, ignoring
14:42:24.142 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=156120 Cipher suits count: 15
14:42:24.143 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 154 bytes to socket channel
14:42:24.217 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/37.209.240.1:443 Read 1388 bytes from socket channel
14:42:24.225 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/37.209.240.1:443 Read 1332 bytes from socket channel
14:42:24.242 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 75 bytes to socket channel
14:42:24.259 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 6 bytes to socket channel
14:42:24.261 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 45 bytes to socket channel
14:42:24.411 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/37.209.240.1:443 Read 51 bytes from socket channel
14:42:24.429 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Established an encrypted connection with a remote server
14:42:24.471 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Certificate chain
14:42:24.481 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Getting or generating endpoint certificate
14:42:24.486 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Establishing an encrypted connection with a local client
14:42:24.513 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=156120 Notify secure renegotiation true
14:42:24.514 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 58 bytes to socket channel
14:42:24.515 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 1058 bytes to socket channel
14:42:24.515 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 9 bytes to socket channel
14:42:25.030 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/127.0.0.1:37393 Closing TCP connection
14:42:25.030 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=156120 Server alert raised. Level: fatal, Description: internal_error internal_error(80)
14:42:25.031 [pool-2-thread-35805] DEBUG com.adguard.commons.b.r - TCP id=156120 Write 7 bytes to socket channel
14:42:25.032 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Connection was closed unexpectedly twice for the last 10 seconds
14:42:25.032 [pool-2-thread-35805] INFO  com.adguard.filter.proxy.ssl.k - TCP id=156120 Adding endpoint com.yandex.browser.alpha_37.209.240.1_443_m.sports.ru to exceptions due to class java.nio.channels.ClosedChannelException: null
14:42:25.035 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Caused by
14:42:25.035 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.ssl.k - TCP id=156120 Caused by

java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:268) ~[na:0.0]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:477) ~[na:0.0]
	at com.adguard.commons.b.r.write(Unknown Source) ~[na:0.0]
	at com.adguard.commons.b.r.write(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.k.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.k.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
14:42:25.036 [pool-2-thread-35805] ERROR com.adguard.filter.proxy.a - TCP id=156120 Error while processing connection. Connection info: com.yandex.browser.alpha /172.16.209.1:41012 /37.209.240.1:443 10149
14:42:25.036 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.l - TCP id=156120 Closing TcpConnectionContext
14:42:25.037 [pool-2-thread-35805] DEBUG com.adguard.filter.proxy.l - TCP id=156120 TcpConnectionContext has been closed
14:43:24.429 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/37.209.240.1:443 Read 31 bytes from socket channel
14:43:24.432 [Thread-5] DEBUG com.adguard.commons.b.s - TCP id=156120 address=/37.209.240.1:443 Closing TCP connection
```

**Comment by ameshkov** [comment]
Handled by the CoreLibs
