### ISSUE TITLE
Crash on the app update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1077]
```
Thread: Thread[main,5,main]; Uncaught exception:

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.adguard.android (has extras) } in com.adguard.android.service.am@9ea9912
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5437) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) ~[na:na]
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/92 from pid=11869, uid=10112 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620) ~[na:0.0]
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183) ~[na:0.0]
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146) ~[na:0.0]
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692) ~[na:0.0]
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107) ~[na:0.0]
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944) ~[na:0.0]
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:797) ~[na:0.0]
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:751) ~[na:0.0]
	at android.app.DownloadManager.openDownloadedFile(DownloadManager.java:1010) ~[na:0.0]
	at com.adguard.android.service.am.onReceive(Unknown Source) ~[na:0.0]
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881) ~[na:0.0]
	... 8 common frames omitted
```

**Comment by nkartyshov** [comment]
Added permission

**Comment by ameshkov** [comment]
Do we really need that permission?
Can't we solve this issue without adding it?

**Comment by nkartyshov** [comment]
@ameshkov Yes, need permission. But can check permission before download and if do not access then request permission.

**Comment by nkartyshov** [comment]
Done. Added an exception trap and redirect to the browser.
