### ISSUE TITLE
Crash in the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1080]
https://forum.adguard.com/index.php?threads/adguard-2-9-1-%C3%9F-crash.19895/

```
Thread[main,5,main]; Uncaught exception:

java.lang.ArrayIndexOutOfBoundsException: length=253; index=-1
	at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:834) ~[na:0.0]
	at android.text.StaticLayout.out(StaticLayout.java:753) ~[na:0.0]
	at android.text.StaticLayout.generate(StaticLayout.java:457) ~[na:0.0]
	at android.text.StaticLayout.<init>(StaticLayout.java:145) ~[na:0.0]
	at android.widget.TextView.makeSingleLayout(TextView.java:6267) ~[na:0.0]
	at android.widget.TextView.makeNewLayout(TextView.java:6124) ~[na:0.0]
	at android.widget.TextView.onMeasure(TextView.java:6500) ~[na:0.0]
	at android.view.View.measure(View.java:16566) ~[na:0.0]
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147) ~[na:0.0]
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1427) ~[na:0.0]
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:713) ~[na:0.0]
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:606) ~[na:0.0]
	at android.view.View.measure(View.java:16566) ~[na:0.0]
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1254) ~[na:0.0]
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:608) ~[na:0.0]
	at android.view.View.measure(View.java:16566) ~[na:0.0]
	at android.widget.ListView.setupChild(ListView.java:1870) ~[na:0.0]
	at android.widget.ListView.makeAndAddView(ListView.java:1793) ~[na:0.0]
	at android.widget.ListView.fillDown(ListView.java:691) ~[na:0.0]
	at android.widget.ListView.fillFromTop(ListView.java:752) ~[na:0.0]
	at android.widget.ListView.layoutChildren(ListView.java:1630) ~[na:0.0]
	at android.widget.AbsListView.onLayout(AbsListView.java:2087) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453) ~[na:0.0]
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453) ~[na:0.0]
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694) ~[na:0.0]
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1548) ~[na:0.0]
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1457) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453) ~[na:0.0]
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694) ~[na:0.0]
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1548) ~[na:0.0]
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1457) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453) ~[na:0.0]
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388) ~[na:0.0]
	at android.view.View.layout(View.java:14884) ~[na:0.0]
	at android.view.ViewGroup.layout(ViewGroup.java:4653) ~[na:0.0]
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2050) ~[na:0.0]
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1807) ~[na:0.0]
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1044) ~[na:0.0]
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5818) ~[na:0.0]
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:768) ~[na:0.0]
	at android.view.Choreographer.doCallbacks(Choreographer.java:581) ~[na:0.0]
	at android.view.Choreographer.doFrame(Choreographer.java:551) ~[na:0.0]
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:754) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:733) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:136) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5333) ~[na:0.0]
	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) ~[na:0.0]
	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
```

**Comment by ameshkov** [comment]
http://stackoverflow.com/questions/14282757/android-list-view-array-index-out-of-bounds-exception-no-clues

**Comment by Revertron** [comment]
Added deprecated option for old devices :-/
AJC-CR-176

**Comment by evgeniy-ADG** [comment]
Filtering log crashing when activating, moving to other app and coming
back. Logs: 1495949

**Comment by Revertron** [comment]
Fixed already, will be in next beta.
