### ISSUE TITLE
VpnService.prepare crashes due to XPosed module

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1084]
We should handle this issue.

```
Thread: Thread[main,5,main]; Uncaught exception:

java.lang.RuntimeException: Unable to start receiver com.adguard.android.receivers.NetworkStateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.connectivity.Vpn.prepare(java.lang.String, java.lang.String)' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2680) ~[na:0.0]
	at android.app.ActivityThread.access$1700(ActivityThread.java:156) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5389) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) ~[na:na]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.connectivity.Vpn.prepare(java.lang.String, java.lang.String)' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1562) ~[na:0.0]
	at android.os.Parcel.readException(Parcel.java:1505) ~[na:0.0]
	at android.net.IConnectivityManager$Stub$Proxy.prepareVpn(IConnectivityManager.java:1716) ~[na:0.0]
	at android.net.VpnService.prepare(VpnService.java:159) ~[na:0.0]
	at com.adguard.android.receivers.BaseReceiver.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.receivers.NetworkStateReceiver.onReceive(Unknown Source) ~[na:0.0]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2673) ~[na:0.0]
	... 10 common frames omitted
```

**Comment by ameshkov** [comment]
Fix: android/bug/1084

**Comment by jbir789** [comment]
Probably not the right place to ask, but I am having the same issue with my app. Could you briefly explain what was the issue with your app, please?

**Comment by ameshkov** [comment]
As I recall, the only thing we could do it wrap all the `VpnService.prepare` calls in `try-catch` blocks to prevent the app crashes. The check was not crucial (it was inside of a receiver).

**Comment by ameshkov** [comment]
```
    /**
     * Checks VpnService.prepare result in a safe manner
     *
     * @param context Application context
     * @return true if VpnService.prepare returns null
     */
    public boolean isVpnServicePrepared(Context context) {
        try {
            return VpnService.prepare(context.getApplicationContext()) == null;
        } catch (Exception ex) {
            LOG.warn("Error preparing vpn service\n", ex);
        }

        return false;
    }
```
