### ISSUE TITLE
Crash: NoSuchMethodError: No virtual method getRemoteAddress()Ljava/net/SocketAddress

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1107]
```
                                                   java.lang.NoSuchMethodError: No virtual method getRemoteAddress()Ljava/net/SocketAddress; in class Ljava/nio/channels/SocketChannel; or its super classes (declaration of 'java.nio.channels.SocketChannel' appears in /system/framework/core-libart.jar)
                                                       at com.adguard.commons.io.SocketChannelOutputStream.write(SocketChannelOutputStream.java:65)
                                                       at com.adguard.android.filtering.vpn.VpnTcpConnection.writeToServer(VpnTcpConnection.java:155)
                                                       at com.adguard.android.filtering.vpn.VpnTcpConnection.access$100(VpnTcpConnection.java:30)
                                                       at com.adguard.android.filtering.vpn.VpnTcpConnection$2.onReceived(VpnTcpConnection.java:88)
                                                       at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpReceive(TcpConnectionImpl.java:652)
                                                       at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcessEstablished(TcpConnectionImpl.java:467)
                                                       at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcess(TcpConnectionImpl.java:418)
                                                       at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpInput(TcpConnectionImpl.java:139)
                                                       at com.adguard.android.filtering.vpn.VpnTcpConnection.tcpInputOpened(VpnTcpConnection.java:219)
                                                       at com.adguard.android.filtering.vpn.VpnTcpConnection.addBrowserInputPacket(VpnTcpConnection.java:117)
                                                       at com.adguard.android.filtering.vpn.BaseVpnConnection$1.run(BaseVpnConnection.java:191)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by ameshkov** [comment]
Added in API level 24
:(

**Comment by ameshkov** [comment]
Resolved
