### ISSUE TITLE
Unknown rule options

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1137]
```
Invalid filter rule: ||walla.co.il^$important,websocket,first-party,domain=animals.walla.co.il|astrology.walla.co.il|b.walla.co.il|cars.walla.co.il|celebs.walla.co.il|e.walla.co.il|elections.walla.co.il|euro.walla.co.il|fashion.walla.co.il|finance.walla.co.il|food.walla.co.il|forums.walla.co.il|fun.walla.co.il|healthy.walla.co.il|home.walla.co.il|judaism.walla.co.il|kids.walla.co.il|mag.walla.co.il|maps.walla.co.il|milon.walla.co.il|movies.walla.co.il|mundial.walla.co.il|nadlan.walla.co.il|news.walla.co.il|nick.walla.co.il|olympics.walla.co.il|search.walla.co.il|sports.walla.co.il|tags.walla.co.il|tech.walla.co.il|travel.walla.co.il|tv-guide.walla.co.il|tv.walla.co.il|usaelections.walla.co.il|viva.walla.co.il|vod.walla.co.il|weather.walla.co.il|www.walla.co.il

java.lang.IllegalArgumentException: Unknown option first-party
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.918 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||ad.doubleclick.net/favicon.ico?ad=$image,important,redirect=2x2-transparent.png,domain=walla.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.923 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||pagead2.googlesyndication.com/pagead/js$script,important,redirect=noopjs,domain=walla.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.934 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||www.mako.co.il^$important,websocket,first-party,domain=www.mako.co.il

java.lang.IllegalArgumentException: Unknown option first-party
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.938 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||ad.doubleclick.net/favicon.ico?ad=$image,important,redirect=2x2-transparent.png,domain=mako.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.942 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||pagead2.googlesyndication.com/pagead/js$script,important,redirect=noopjs,domain=mako.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.948 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||www.calcalist.co.il^$important,websocket,first-party,domain=www.calcalist.co.il

java.lang.IllegalArgumentException: Unknown option first-party
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.952 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||ad.doubleclick.net/favicon.ico?ad=$image,important,redirect=2x2-transparent.png,domain=calcalist.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.959 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||pagead2.googlesyndication.com/pagead/js$script,important,redirect=noopjs,domain=calcalist.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.974 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||www.yad2.co.il^$important,websocket,first-party,domain=www.yad2.co.il

java.lang.IllegalArgumentException: Unknown option first-party
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.980 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||ad.doubleclick.net/favicon.ico?ad=$image,important,redirect=2x2-transparent.png,domain=yad2.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.988 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||pagead2.googlesyndication.com/pagead/js$script,important,redirect=noopjs,domain=yad2.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.991 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||yad2.co.il/js-new/showAds.js$script,redirect=silent-noeval.js,domain=yad2.co.il

java.lang.IllegalArgumentException: Unknown option redirect
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.w(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.s(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:54.994 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: |blob:$first-party,important,domain=www.bizportal.co.il

java.lang.IllegalArgumentException: Unknown option first-party
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:55.473 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: data:$popup,domain=eztv-proxy.net,eztv.ag,eztv.ch,eztv.it,eztv.tf,eztv.yt

java.lang.IllegalArgumentException: Unknown option eztv.ag
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.w(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.s(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:55.862 [pool-2-thread-2251] WARN  com.adguard.filter.rules.h - Error creating filter rule lps.sbro.me##.content__back_vis:after:

java.lang.IllegalArgumentException: Unknown pseudo class: .content__back_vis:after
	at com.adguard.filter.rules.d.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.h.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
01:18:55.889 [pool-2-thread-2251] WARN  c.a.filter.rules.UrlFilterRule - Invalid filter rule: ||saveinter.net^$domaina=kamaihd.net

java.lang.IllegalArgumentException: Unknown option domaina
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.w(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.rules.UrlFilterRule.s(Unknown Source) ~[na:0.0]
	at com.adguard.filter.a.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.j.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.j(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.aa.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ab.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.u.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Resolved, no more stack traces when logging level is default
