### ISSUE TITLE
Unnecessary exception in the log file

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1176]
```
10:34:23.688 [pool-3-thread-454] INFO  com.adguard.filter.proxy.a - Proxy server has been closed
10:34:24.250 [pool-3-thread-437] ERROR com.adguard.filter.proxy.n - Error accepting connection

java.nio.channels.ClosedChannelException: null
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:130) ~[na:0.0]
	at com.adguard.commons.b.s.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.b.q.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.l.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.n$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fixed
