### ISSUE TITLE
Adguard crashes and restarts on a launch of Chrome or other data-consuming apps 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1196]
Logs and the conversation history: 1542731

"androidVersion" : "5.0.1 (sdk=21)",
 "deviceName" : "asus Z00D",
"versionName" : "2.9.64",
"proxyMode" : false

Doesn't happen with other VPN apps, only with Adguard.

**Comment by TPS** [comment]
I'm suddenly having similar to this for last week or so, too, but I thought perhaps I added a user filter that's overwhelming AG.  Also, after restart, filtering log is wiped (@ least per UI), so I'm not sure what I can send.  Anyway, next time I notice, I'll send what I have.

**Comment by ameshkov** [comment]
Just before AG is crashed, I see this in the log:
```
15:03:05.849 [Thread-2577] WARN  c.a.a.f.vpn.FilteringVpnService - Interrupted system call:

java.io.InterruptedIOException: Error Interrupted system call occurred while polling file descriptor 58
	at com.adguard.android.filtering.commons.NativeUtils.readFd(Native Method) ~[na:0.0]
	at com.adguard.android.filtering.vpn.e.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.h(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@evgeniy-ADG we need to get the system log (logcat) in order to find out what's wrong with it
