### ISSUE TITLE
Adguard can't start VPN on IPv6 network (Android 4.4.2)

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1267]
This happens with 2.9.111 beta only, works fine on 2.9.70

logs: [adguard (1).log.zip]
(https://github.com/AdguardTeam/AdguardForAndroid/files/1063732/adguard.1.log.zip)

> 21:08:20.956 [Thread-632] INFO  c.a.android.filtering.commons.e - Found IPv6 address for network [wlan0][5][/2001:db8:7c02:1:3219:66ff:fef9:23f2%5%5][/fe80::3219:66ff:fef9:23f2%wlan0%5][/2001:db8:7c02:1:fdfb:c0:5272:2a04%5%5][/192.168.10.183]
21:08:20.957 [Thread-632] INFO  c.a.android.vpn.AdguardVpnService - Adding default IPv6 route
21:08:20.964 [Thread-632] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: VPN_CONFIG_ERROR
21:08:21.003 [Thread-632] INFO  com.adguard.android.service.aq - Updating widgets for VPN_CONFIG_ERROR protection
21:08:21.086 [Thread-632] ERROR c.a.a.f.vpn.FilteringVpnService - Error building vpn interface

> java.lang.IllegalArgumentException: Bad LinkAddress params /0.0.0.0/96
	at android.net.LinkAddress.init(LinkAddress.java:46) ~[na:0.0]
	at android.net.LinkAddress.<init>(LinkAddress.java:54) ~[na:0.0]
	at android.net.RouteInfo.<init>(RouteInfo.java:103) ~[na:0.0]
	at android.net.RouteInfo.<init>(RouteInfo.java:112) ~[na:0.0]
	at android.net.VpnService$Builder.addRoute(VpnService.java:366) ~[na:0.0]
	at com.adguard.android.vpn.AdguardVpnService.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.vpn.AdguardVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]

**Comment by ameshkov** [comment]
Fixed, we'll simply ignore this error if it happens. Review ID: AFA-CR-26
