### ISSUE TITLE
crash on network type changes 2.9.111b

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1272]
since 2.9b, adguard seems to crash on network type changes like wifi to 4g and back again

[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066590/state.txt)
[debug (35).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066591/debug.35.txt)
CustomerID: 1350712

**Comment by ameshkov** [comment]
```
10:39:32.060 [pool-2-thread-264] ERROR com.adguard.android.commons.c - Thread: Thread[pool-2-thread-264,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adguard.android.filtering.filter.i.a()' on a null object reference
	at com.adguard.android.filtering.vpn.FilteringVpnService.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@Michael23456 please ask user to collect "record everything"-level log

**Comment by Michael23456** [comment]
we are waiting for an answer from the customer

**Comment by ameshkov** [comment]
Added a simple check to prevent it. If it ever happens with a newer builds, please reopen this issue.
