### ISSUE TITLE
Crash on restarting AG protection: Missing event handler for an annotated method

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1368]
```
09:32:29.243 [pool-2-thread-6937] ERROR c.a.a.c.CustomExceptionHandler - Thread: Thread[pool-2-thread-6937,5,main]; Uncaught exception:

java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class com.adguard.android.filter.AdguardProxyServer registered?
	at com.squareup.otto.Bus.unregister(Bus.java:290) ~[na:0.0]
	at com.adguard.android.filtering.events.Mediator.unregisterListener(Mediator.java:64) ~[na:0.0]
	at com.adguard.android.filter.AdguardProxyServer.close(AdguardProxyServer.java:91) ~[na:0.0]
	at com.adguard.android.filtering.filter.FilteringProxyServer$1.run(FilteringProxyServer.java:83) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by Revertron** [comment]
Done, review accepted.
