### ISSUE TITLE
NPE in DnsUpstreamServer

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1381]
### Steps to reproduce
Unknown

### Expected behavior
Starting protection service as normal

### Actual behavior
The protection service can not start

<details><summary>Logs:</summary>

DnsInfo from preferences:
{"address":null,"anycast":false,"description":null,"dnsCryptProviderName":null,"dnsCryptPublicKey":null,"encrypted":false,"id":"custom","name":null,"website":null}

And log:
```
[VpnService-main] Error building vpn interface
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
    at com.adguard.android.filtering.dns.DnsUpstreamServer.setUpstreamServers(DnsUpstreamServer.java:192) ~[na:0.0]
    at com.adguard.android.filtering.dns.DnsUpstreamServer.<init>(DnsUpstreamServer.java:78) ~[na:0.0]
    at com.adguard.android.filtering.dns.FilteringDnsProxyServer.start(FilteringDnsProxyServer.java:82) ~[na:0.0]
    at com.adguard.android.vpn.AdguardVpnService.startFilteringDnsProxyServer(AdguardVpnService.java:216) ~[na:0.0]
    at com.adguard.android.vpn.AdguardVpnService.buildVpnService(AdguardVpnService.java:164) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.setupVpn(FilteringVpnService.java:247) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.access$000(FilteringVpnService.java:48) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(FilteringVpnService.java:158) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```
</details>

### Customer ID 
Me

### Your environment

* Adguard version: 2.10.18
* Adguard filtering mode: VPN
* Device model: SDK emulator
* Operating system and version 7.1.1
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-82
