### ISSUE TITLE
Doesn’t create log file on android N

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#1383]
### Steps to reproduce
Mobile phone with android N and enable a "Recording everything"

### Expected behavior
Log file created

### Actual behavior
Log file doesn’t create

```
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,904 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.%d.log'.
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,904 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,905 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Aug 17 16:53:09 GMT+03:00 2017
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,908 |-INFO in com.adguard.android.commons.FailoverRollingFileAppender[file] - Active log file name: /storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,908 |-INFO in com.adguard.android.commons.FailoverRollingFileAppender[file] - File property is set to [/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log]
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,914 |-ERROR in com.adguard.android.commons.FailoverRollingFileAppender[file] - Failed to create parent directories for [/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log]
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out: 16:53:09,916 |-ERROR in com.adguard.android.commons.FailoverRollingFileAppender[file] - openFile(/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log,true) failed java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log (No such file or directory)
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out:     at java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log (No such file or directory)
08-17 16:53:09.981 18671-18671/com.adguard.android I/System.out:     at     at java.io.FileOutputStream.open(Native Method)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.FileAppender.openFile(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.FileAppender.start(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.rolling.RollingFileAppender.start(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.action.AppenderAction.end(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
08-17 16:53:09.982 18671-18671/com.adguard.android I/System.out:     at     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at com.adguard.android.AdguardApplication.<clinit>(AdguardApplication.java:31)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at java.lang.Class.newInstance(Native Method)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5436)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.os.Handler.dispatchMessage(Handler.java:102)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.os.Looper.loop(Looper.java:154)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at android.app.ActivityThread.main(ActivityThread.java:6178)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at java.lang.reflect.Method.invoke(Native Method)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-17 16:53:09.983 18671-18671/com.adguard.android I/System.out:     at     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

### Customer ID 
me

### Your environment
* Adguard version: 2.1016
* Adguard filtering mode: VPN or Proxy
* Device model: Xiaomi Redmi Note 3
* Operating system and version  Android 7.1.2
* Rooted

**Comment by ameshkov** [comment]
https://stackoverflow.com/questions/40087355/android-mkdirs-not-working

**Comment by ameshkov** [comment]
We should also update the knowledge base article once it is fixed:
https://kb.adguard.com/en/android/solving-problems/log

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-84

**Comment by ameshkov** [comment]
We should also add an "Export log and system info" item under the "Logging level" (in the advanced settings section).

**Name:**
`Export log and system info`

**Description:**
`Exports AdGuard's log files and system information into a file.`

Tap on this item should bring up an export location chooser activity.
Default file name: `adguard_logs.zip`

**Comment by ameshkov** [comment]
Use these classes:
https://developer.android.com/reference/java/util/zip/ZipFile.html

But keep an eye on methods min api level.

**Comment by TPS** [comment]
May I suggest default file name: `adguard_logs_DDDD-TTTT.zip` for multiple captures?

**Comment by ameshkov** [comment]
@TPS sure, thanks for the tip!

**Comment by nkartyshov** [comment]
done

**Comment by ameshkov** [comment]
@nkartyshov there should be a progress dialog when you are exporting files

**Comment by nkartyshov** [comment]
Added progress dialog for export logs
