### ISSUE TITLE
Crash on Android v4.X

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1447]
```
09-16 14:30:16.844 W/dalvikvm( 8799): threadid=1: thread exiting with uncaught exception (group=0x417d0e48)
09-16 14:30:16.844 E/AndroidRuntime( 8799): FATAL EXCEPTION: main
09-16 14:30:16.844 E/AndroidRuntime( 8799): Process: com.adguard.android, PID: 8799
09-16 14:30:16.844 E/AndroidRuntime( 8799): java.lang.NoClassDefFoundError: org.slf4j.helpers.MessageFormatter
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.pattern.MessageConverter.convert(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.pattern.MessageConverter.convert(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.core.pattern.FormattingConverter.write(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.PatternLayout.doLayout(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.PatternLayout.doLayout(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.android.LogcatAppender.append(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.android.LogcatAppender.append(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.Logger.callAppenders(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.Logger.filterAndLog_1(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at ch.qos.logback.classic.Logger.info(Unknown Source)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at com.adguard.android.filtering.commons.LogUtils.configureLogger(LogUtils.java:259)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at com.adguard.android.AdguardApplication.onCreate(AdguardApplication.java:49)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4415)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.ActivityThread.handleBindApplication(Native Method)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.ActivityThread.access$1500(ActivityThread.java:139)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.os.Looper.loop(Looper.java:136)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
09-16 14:30:16.844 E/AndroidRuntime( 8799): 	at dalvik.system.NativeStart.main(Native Method)
09-16 14:30:16.854 W/ActivityManager( 5986):   Force finishing activity com.adguard.android/.ui.SplashActivity
```

**Comment by nkartyshov** [comment]
Enabling multidex has solved problem on the android 4.4 or lower
