### ISSUE TITLE
Error while generating a domain certificate

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1451]
Here is how it looks like:

```
10:38:02.853 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.a - TCP id=1000029 Server has accepted new tcp connection. Connection info=com.android.chrome /192.168.1.62:37269 /173.194.222.105:443 10030
10:38:02.854 [Thread-523] DEBUG com.adguard.commons.b.r - TCP id=1000029 address=/192.168.1.62:37269 Read 202 bytes from the socket channel
10:38:02.855 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.a - TCP id=1000029 Accepting incoming SSL connection
10:38:02.858 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=1000029 Received ClientHello:
TLS ClientHello
  Record Layer Version: 0x0301
  Version: 0x0303
  Server Name: www.google.com
  ALPN: http/1.1, h2
  Random Bytes: 9fba903c6ed9f93ba1c8177a81e76cc0a6b43d5e47689131d1eb5b44110afb9f
  Cipher Suites:
    0x9a9a, 0xcca9, 0xcca8, 0xc02b, 0xc02f, 0xc02c, 0xc030, 0xc013, 0xc014, 0x009c, 0x009d, 0x002f, 0x0035, 0x000a
  Compression Methods: 0x0000
  Extensions:
      0x000b -> [1, 0]
      0x0017 -> []
      0x0000 -> [0, 17, 0, 0, 14, 119, 119, 119, 46, 103, 111, 111, 103, 108, 101, 46, 99, 111, 109]
      0x000d -> [0, 18, 4, 3, 8, 4, 4, 1, 5, 3, 8, 5, 5, 1, 8, 6, 6, 1, 2, 1]
      0x9a9a -> []
      0x0005 -> [1, 0, 0, 0, 0]
      0xff01 -> [0]
      0x0023 -> []
      0x7550 -> []
      0x000a -> [0, 8, -70, -70, 0, 29, 0, 23, 0, 24]
      0x0010 -> [0, 12, 2, 104, 50, 8, 104, 116, 116, 112, 47, 49, 46, 49]
      0x3a3a -> [0]
      0x0012 -> []

10:38:02.860 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=1000029 Creating new remote endpoint
10:38:02.883 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.r - TCP id=1000029 Session cache hit: true
10:38:02.884 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.o - TCP id=1000029 Client provided unsupported cipher: 0x9a9a, ignoring
10:38:02.885 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.o - TCP id=1000029 Client provided unsupported cipher: 0xcca9, ignoring
10:38:02.885 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.o - TCP id=1000029 Client provided unsupported cipher: 0xcca8, ignoring
10:38:02.885 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.o - TCP id=1000029 Cipher suits count: 11
10:38:02.886 [pool-2-thread-4] DEBUG com.adguard.commons.b.q - TCP id=1000029 Write 181 bytes to the socket channel /173.194.222.105:443
10:38:02.893 [Thread-523] DEBUG com.adguard.commons.b.r - TCP id=1000029 address=/173.194.222.105:443 Read 143 bytes from the socket channel
10:38:02.896 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.o - Secure renegotiation: true
10:38:02.897 [pool-2-thread-4] DEBUG com.adguard.commons.b.q - TCP id=1000029 Write 6 bytes to the socket channel /173.194.222.105:443
10:38:02.899 [pool-2-thread-4] DEBUG com.adguard.commons.b.q - TCP id=1000029 Write 45 bytes to the socket channel /173.194.222.105:443
10:38:02.902 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.r - TCP id=1000029 Session resumption: true
10:38:02.904 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=1000029 Established an encrypted connection with a remote server
10:38:02.905 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=1000029 Certificate chain
0:    C=US,ST=California,L=Mountain View,O=Google Inc,CN=www.google.com
1:    C=US,O=Google Inc,CN=Google Internet Authority G2
2:    C=US,O=GeoTrust Inc.,CN=GeoTrust Global CA

10:38:02.906 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.ssl.m - TCP id=1000029 Getting or generating endpoint certificate
10:38:02.910 [pool-2-thread-4] ERROR com.adguard.filter.proxy.a - TCP id=1000029 Error while processing connection. Connection info: com.android.chrome /192.168.1.62:37269 /173.194.222.105:443 10030

java.io.IOException: No X509 certificate in the input stream! Loaded null
	at com.adguard.filter.proxy.ssl.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.a.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.g.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.m.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.m.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.m.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.h.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.h.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.o.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.o$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
10:38:02.912 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.m - TCP id=1000029 Closing TcpConnectionContext
10:38:02.913 [pool-2-thread-4] DEBUG com.adguard.filter.proxy.m - TCP id=1000029 TcpConnectionContext has been closed
```

**Comment by ameshkov** [comment]
Something wrong happens on certificate generation

**Comment by ameshkov** [comment]
It seems that the domain certificates cache file was damaged

**Comment by ameshkov** [comment]
Fixed in adguard-android/pull-requests/82
