### ISSUE TITLE
Crash while trying to clear Firewall stats with AG disabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1462]
```
03:08:25.794 [main] ERROR com.adguard.android.c.d - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adguard.android.ServiceManager.a(com.adguard.android.model.e)' on a null object reference
	at com.adguard.android.service.an.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.an.c(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.SettingsFirewallFragment$1.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.utils.c$2.onClick(Unknown Source) ~[na:0.0]
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(Unknown Source) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5481) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) ~[na:0.0]
```

**Comment by Revertron** [comment]
Thorough investigation shows, that in the new beta it is impossible to get this NPE.
The needed checks are in theirs right places.
