### ISSUE TITLE
Update crash on KitKat and Lollipop

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1466]
```
18:24:43.313 [main] WARN  com.adguard.android.service.l - Cannot get cpu.active value

java.lang.NoSuchMethodException: getNumSpeedStepsInCpuCluster [int]
    at java.lang.Class.getMethod(Class.java:664) ~[na:0.0]
    at java.lang.Class.getMethod(Class.java:643) ~[na:0.0]
    at com.adguard.android.service.m.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.service.m.<init>(Unknown Source) ~[na:0.0]
    at com.adguard.android.service.m.<init>(Unknown Source) ~[na:0.0]
    at com.adguard.android.service.l.<init>(Unknown Source) ~[na:0.0]
    at com.adguard.android.b.x(Unknown Source) ~[na:0.0]
    at com.adguard.android.AdguardApplication.onCreate(Unknown Source) ~[na:0.0]
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) ~[na:0.0]
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4661) ~[na:0.0]
    at android.app.ActivityThread.access$1500(ActivityThread.java:156) ~[na:0.0]
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) ~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
    at android.app.ActivityThread.main(ActivityThread.java:5389) ~[na:0.0]
    at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
```

**Comment by Revertron** [comment]
This is not an update error. This is an error from BatteryService.
I've already proposed to hide and disable it for old Androids...
