### ISSUE TITLE
Unexpected exception in the onTcpConnectRequest handler

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1474]
```
01:08:26.120 [pool-14-thread-89] ERROR c.a.a.f.vpn.FilteringVpnService - TCP id=1813 Unexpected exception in the onTcpConnectRequest handler

java.lang.NullPointerException: null
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019) ~[na:0.0]
    at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014) ~[na:0.0]
    at com.adguard.android.filtering.filter.c.a(Unknown Source:7) ~[na:0.0]
    at com.adguard.android.filtering.vpn.a.onTcpConnectRequest(Unknown Source:71) ~[na:0.0]
    at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl$Callbacks$1.run(Unknown Source:16) ~[na:0.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) ~[na:0.0]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by ameshkov** [comment]
The log is from old beta verison, the issue was resolved in the latest one
