### ISSUE TITLE
2.10.104 crashes on exporting settings

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1495]
### Steps to reproduce

1. Try to export the settings
2. See it crashing

> При клике "Экспортировать и импортировать настройки" вылетает в общие настройки. Время 20:33
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1344013/debug.txt)

### Expected behavior

It does not crash and exporting settings

### Actual behavior

It crashes.

### Your environment

* Adguard version: 2.10.104
* Adguard filtering mode: VPN
* Device model: OnePlus A0001
* Operating system and version: 7.1.2

**Comment by vozersky** [comment]
can't rep, need logcat @evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
ок

**Comment by Xophile** [comment]
Working fine here on Samsung Galaxy S7 Edge

**Comment by darkulish** [comment]
customer recored log via catlog 
problem remaing only on Android 7.1.2

**Comment by vozersky** [comment]
@darkulish still able to reproduce with the latest release?

**Comment by vozersky** [comment]
@nkartyshov please take a look at the logcat

**Comment by nkartyshov** [comment]
I see a system crash in the log after the user has selected the folder in which the settings will be exported.

```
09-29 22:58:25.896 I/ActivityManager( 2469): START u0 {act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/*} from uid 10084 on display 0
09-29 22:58:29.449 W/WindowManager( 2469): Attempted to remove non-existing token: android.os.Binder@cc9ec9e
09-29 22:58:30.317 I/GoogleURLConnFactory( 4813): Using platform SSLCertificateSocketFactory
09-29 22:58:30.321 I/GoogleURLConnFactory( 4813): Using platform SSLCertificateSocketFactory
09-29 22:58:30.488 I/GCM     ( 4813): Ack for not saved message 20
09-29 22:58:30.608 W/System  ( 4813): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
09-29 22:58:30.726 W/Conscrypt( 4813): Could not set socket write timeout:
09-29 22:58:30.730 W/Conscrypt( 4813):    java.lang.reflect.Method.invoke(Native Method)
09-29 22:58:30.730 W/Conscrypt( 4813):    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11517438:13)
09-29 22:58:30.993 W/Conscrypt( 4813): Could not set socket write timeout:
09-29 22:58:30.994 W/Conscrypt( 4813):    java.lang.reflect.Method.invoke(Native Method)
09-29 22:58:30.994 W/Conscrypt( 4813):    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11517438:13)
09-29 22:58:31.783 W/System.err( 4813): FileClientSessionCache: Error reading session data for play.googleapis.com from /data/user/0/com.google.android.gms/app_sslcache/play.googleapis.com.443.
09-29 22:58:31.784 W/System.err( 4813): java.io.FileNotFoundException: /data/user/0/com.google.android.gms/app_sslcache/play.googleapis.com.443 (No such file or directory)
09-29 22:58:31.786 W/System.err( 4813): 	at java.io.FileInputStream.open(Native Method)
09-29 22:58:31.786 W/System.err( 4813): 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
09-29 22:58:31.786 W/System.err( 4813): 	at com.android.org.conscrypt.FileClientSessionCache$Impl.getSessionData(FileClientSessionCache.java:158)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.org.conscrypt.ClientSessionContext.getSession(ClientSessionContext.java:84)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.org.conscrypt.SSLParametersImpl.getCachedClientSession(SSLParametersImpl.java:783)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.org.conscrypt.SSLParametersImpl.getSessionToReuse(SSLParametersImpl.java:430)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:334)
09-29 22:58:31.787 W/System.err( 4813): 	at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:198)
09-29 22:58:31.787 W/System.err( 4813): 	at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:443)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.Connection.connectTls(Connection.java:224)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.Connection.connect(Connection.java:172)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
09-29 22:58:31.787 W/System.err( 4813): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
09-29 22:58:31.796 W/System.err( 4813): 	at tqb.a(:com.google.android.gms@11517438:50)
09-29 22:58:31.796 W/System.err( 4813): 	at tqb.a(:com.google.android.gms@11517438:76)
09-29 22:58:31.796 W/System.err( 4813): 	at tqb.execute(:com.google.android.gms@11517438:8)
09-29 22:58:31.796 W/System.err( 4813): 	at tqb.execute(:com.google.android.gms@11517438:7)
09-29 22:58:31.796 W/System.err( 4813): 	at krf.a(:com.google.android.gms@11517438:27)
09-29 22:58:31.796 W/System.err( 4813): 	at krf.a(:com.google.android.gms@11517438:198)
09-29 22:58:31.796 W/System.err( 4813): 	at krf.a(:com.google.android.gms@11517438:224)
09-29 22:58:31.796 W/System.err( 4813): 	at krf.a(:com.google.android.gms@11517438:226)
09-29 22:58:31.796 W/System.err( 4813): 	at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.a(:com.google.android.gms@11517438:18)
09-29 22:58:31.796 W/System.err( 4813): 	at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.b(:com.google.android.gms@11517438:20)
09-29 22:58:31.796 W/System.err( 4813): 	at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.a(:com.google.android.gms@11517438:29)
09-29 22:58:31.796 W/System.err( 4813): 	at ssv.run(:com.google.android.gms@11517438:1)
09-29 22:58:31.796 W/System.err( 4813): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-29 22:58:31.796 W/System.err( 4813): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-29 22:58:31.796 W/System.err( 4813): 	at java.lang.Thread.run(Thread.java:761)
09-29 22:58:32.618 I/ActivityManager( 2469): START u0 {act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras)} from uid 10084 on display 0
```

**Comment by Revertron** [comment]
> the problem remains only on Android 7.1.2.
We did fix that. At least in master.
