### ISSUE TITLE
Unexpected exception in the onUdpConnectRequest handler

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1501]
```
21:02:36.296 [pool-11-thread-49] ERROR c.a.a.f.vpn.FilteringVpnService - UDP id=1141 Unexpected exception in the onUdpConnectRequest handler

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.adguard.filter.b.c.c()' on a null object reference
	at com.adguard.android.filtering.vpn.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.a.onUdpConnectRequest(Unknown Source) ~[na:0.0]
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl$Callbacks$4.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by Revertron** [comment]
Fixed.
