### ISSUE TITLE
Unexpected crash in the apps management section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1538]
```
16:41:51.935 [main] ERROR com.adguard.android.c.d - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adguard.android.model.a.a(com.adguard.android.model.a)' on a null object reference
	at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.onViewCreated(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source) ~[na:0.0]
	at android.support.v4.app.BackStackRecord.executeOps(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6186) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) ~[na:0.0]
```

**Comment by Revertron** [comment]
Fixed.
