### ISSUE TITLE
Crash in Amazon version

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1608]
### Steps to reproduce
1. Install Amazon version
2. Clear data
3. Import previously exported settings
4. Go to license activity

### Expected behavior
Works normally

### Actual behavior
Crashes

<details><summary>Log</summary>
```
19:43:11.385 [main] ERROR com.adguard.android.c.d - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.RuntimeException: Unable to resume activity {com.adguard.android/com.adguard.android.ui.AdguardPremiumInfoActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3443) ~[na:0.0]
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3483) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2746) ~[na:0.0]
	at android.app.ActivityThread.-wrap12(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1487) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6164) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) ~[na:0.0]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249) ~[na:0.0]
	at com.adguard.android.service.af.l(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.license.f.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.license.AdguardLicenseServiceImpl.isTrialAvailable(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.AdguardPremiumInfoActivity.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.AdguardPremiumInfoActivity.onResume(Unknown Source) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270) ~[na:0.0]
	at android.app.Activity.performResume(Activity.java:6824) ~[na:0.0]
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3420) ~[na:0.0]
	... 10 common frames omitted
```
</details>

### Customer ID 
@TPS 

### Your environment
* Adguard version: 2.10.171
* Adguard filtering mode: N/A
* Device model: Nextbit Robin
* Operating system and version: 7.1.1
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by TPS** [comment]
I _think_ this is resolved via .175, but, after update, I still got a couple of (what I feel are) random crashes.  Now it's been stable for a while, but I'll report back if there're further problems.

**Comment by ameshkov** [comment]
Could you plz send us the log file so that we could check what've caused these crashes?

**Comment by TPS** [comment]
Just sent, referring your comment URL (https://github.com/AdguardTeam/AdguardForAndroid/issues/1608#issuecomment-346658498) above.

**Comment by vozersky** [comment]
@TPS did you have a chance to check the .176 build (Amazon test) We've added a fix for this issue.

**Comment by TPS** [comment]
Sorry, got all caught up in Thanksgiving 🦃, then Black Friday / Cyber Monday & forgot to check back in: I've not had a crash nor problem since before my last bug report (other than AG interfering w/ my eBates referals, but that's easily remedied by toggling filtering for the correct  1 second 😉) .

**Comment by Revertron** [comment]
I think we can close this as fixed then.
