### ISSUE TITLE
Error on VPN reconfiguration: failed to bind TUN pcb

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1634]
Customer ID: 1660692

```
13:03:16.378 [pool-1-thread-1] INFO  c.a.android.vpn.AdguardVpnService - Success building vpn interface
13:03:16.380 [pool-1-thread-1] ERROR Native.TCPIP.TCPRAW - init: failed to bind TUN pcb
13:03:16.381 [pool-1-thread-1] ERROR Native.TCPIP.TCPMNGR - tcp raw initialization has failed
13:03:16.381 [pool-1-thread-1] ERROR Native.TCPIP.API - open: failed
13:03:16.381 [pool-1-thread-1] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: VPN_CONFIG_ERROR
13:03:16.423 [pool-1-thread-1] INFO  com.adguard.android.service.bb - Updating widgets for VPN_CONFIG_ERROR protection
13:03:16.442 [pool-1-thread-1] ERROR c.a.a.f.vpn.FilteringVpnService - Error building vpn interface

java.lang.RuntimeException: Can't create tcpip context
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.init(Native Method) ~[na:0.0]
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.c(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$3.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:762) ~[na:0.0]
```

**Comment by sfionov** [comment]
Found what the problem is. I can only happen if there are time-wait connections with destination port matching our internal reserved port number. Reserved port number is not used at runtime, only at init phase to correctly add callbacks to LWIP.

**Comment by ameshkov** [comment]
One more issue just like that:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=68270987
