### ISSUE TITLE
Connection stuck on upload: java.net.SocketTimeoutException: Socket write timed out

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#164]
[debug (13).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/29805/debug.13.txt)

It seems that write timeout is too small?

Look at this (pool-2-thread-201):
```
21:12:50.979 [pool-2-thread-201] DEBUG com.adguard.android.TcpPacketLog - TCP id=1276 [Packet] [OUT] ESTABLISHED TCP 172.16.16.1:55766 > 94.100.178.248:443 [ACK] seq=664251 ack=134 win=1373 len=4340
21:12:51.022 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:51.551 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:52.203 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:52.573 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:52.807 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:53.038 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:53.593 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:53.757 [pool-2-thread-193] DEBUG com.adguard.commons.io.IoUtils - Write 8192 bytes to /94.100.178.248
21:12:53.989 [pool-2-thread-201] ERROR c.a.a.filtering.commons.LogUtils - TCP id=1276 Error while processing vpn data
java.net.SocketTimeoutException: Socket write timed out
	at com.adguard.commons.io.SocketChannelOutputStream.write(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.BaseVpnConnection.writeToServer(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection$2.onReceived(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpReceive(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcessEstablished(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcess(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpInput(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.tcpInputOpened(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.addBrowserInputPacket(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.BaseVpnConnection$1.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44369258

**Comment by ameshkov** [comment]
Increased to 10 seconds.

**Comment by ameshkov** [comment]
Increased timeout now cause #238

**Comment by ameshkov** [comment]
I think I've fixed it in the latest build

**Comment by ameshkov** [comment]
The same issue with download large files (proxy mode):
```
18:17:13.398 [pool-2-thread-1] DEBUG com.adguard.commons.io.IoUtils - Error while tunnelling traffic
java.net.SocketTimeoutException: Socket write timed out
	at com.adguard.commons.io.SocketChannelOutputStream.write(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
	at com.adguard.commons.io.IoUtils.tunnel(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.BaseHttpsProxyServer.tunnelConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.BaseHttpsProxyServer.processSslConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.BaseHttpsProxyServer.acceptIncomingConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener.acceptConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener.access$100(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

Ticket ID: XGC-225-22471

**Comment by ameshkov** [comment]
Test build with write timeout increased to 30 seconds:
https://static.adguard.com/android/release/adguard_issue164.apk

**Comment by ameshkov** [comment]
Now it works good
