### ISSUE TITLE
Crash caused (possibly) by a huge number of apps installed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1659]
Customer ID: 1682075

Report:
> When you enter the App Admin menu, Apps are forcefully terminated
while loading the App list. Currently, there are 700 apps installed on
my smartphone. If there are many installed apps, you may not be able
to call up the app list normally.

```
Uncaught exception:

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:995) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836) ~[na:0.0]
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62) ~[na:0.0]
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143) ~[na:0.0]
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132) ~[na:0.0]
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219) ~[na:0.0]
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268) ~[na:0.0]
	at com.adguard.android.d.b.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment$7.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:762) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@Revertron could it be that we create a DbHelper for every app on the list? That's weird, I know, but what if?

**Comment by Revertron** [comment]
More descriptors are involved in socket connections and in /proc/net/tcp file parsing.
I don't think that the DB was the issue.

**Comment by ameshkov** [comment]
@Revertron tbh, I suppose that it might be caused by us making additional SQL request on every app and opening an additional DB connection for that.
