### ISSUE TITLE
Update filters translations

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1762]
In the past, AdGuard team wrongly used Simplified Chinese translations (locale 'zh-CN' or 'zh') in Traditional Chinese language file (locale 'zh-TW').
Especially, about the translations of filters.
They're Simplified Chinese translations or low quality of Traditional Chinese translations for Ad Blocker's filters.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hqrn6VZ.png)
</details><br/>

I early completed the Traditional Chinese translations of filters.
AdGuard Pro for iOS already starts to remove Simplified Chinese translations from Traditional Chinese language file.
It's time that AdGuard for Android, Windows, Mac, Browser Extension and Content Blocker do so, too.
locale 'zh-CN' or 'zh' is Simplified Chinese for China.
'zh-TW' is Traditional Chinese for Taiwan.

Please correctly use 'zh-TW' for filters' translations in Traditional Chinese language file of any platforms. 

Thanks a lot!

**Comment by ameshkov** [comment]
@nkartyshov make sure that we use `zh-tw` and not just `zh` to get the filters translations.

**Comment by nkartyshov** [comment]
For Traditional Chinese, we use `zh-tw` to get filter translations.

**Comment by lancelot-moon** [comment]
Please let me check the content of zh-tw for ad blocker's filters.

It's because that Simplified Chinese translations and low quality of Traditional Chinese translations are mixed in now AdGuard for Android.

We need to apply my new Traditional Chinese translations for filters.

You must update zh-tw for filters.

**Comment by ameshkov** [comment]
> For Traditional Chinese, we use zh-tw to get the filters translations.

That's okay, but you need to make sure that the language code format you use is the same as in the localization file.

`langCode.toLowerCase().replace("_", "-")`

**Comment by nkartyshov** [comment]
@ameshkov The language code is the same as in the filter localization file. In the full localization we use "-" separator.

**Comment by ameshkov** [comment]
@nkartyshov my point is that we need to enforce this format from the client side. What if it ever changes on the server side?

**Comment by nkartyshov** [comment]
What do you mean by the north side? Now the filters localization is select from the database.
We can add one condition to the selection of the localization of the filter with replace symbol `-` by `_`

**Comment by ameshkov** [comment]
@nkartyshov make sure that we load the filters metadata and translations from here:

https://filters.adtidy.org/android/filters.json
https://filters.adtidy.org/android/filters_i18n.json

**Comment by lancelot-moon** [comment]
@ameshkov 
https://filters.adtidy.org/android/filters.json
There is only:
{
			"tagId": 31,
			"keyword": "lang:zh"
		},

I think that you should add
{
			"tagId": xx,
			"keyword": "**lang:zh_TW**"
		},

After all, Traditional Chinese (zh_TW) and Simplified Chinese (zh or zh_CN) are different.
You should let zh_TW be individual, which is maybe better.

**Comment by lancelot-moon** [comment]
I read the changelog of AdGuard v2.11.64η.
It seems that you tried to solve the filters' translations in AdGuard v2.11.64η.
But you are failed.
They're still Simplified Chinese translations and old low quality of Traditional Chinese translations.
Really hope that you can apply my new Traditional Chinese translations soon.
Thanks a lot!

**Comment by ameshkov** [comment]
@Revertron 

It also crashes:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard.android/com.adguard.android.ui.MainActivity}: android.view.InflateException: Binary XML file line #38: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) ~[na:0.0]
	at android.app.ActivityThread.access$800(ActivityThread.java:151) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:135) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5349) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) ~[na:0.0]
Caused by: android.view.InflateException: Binary XML file line #38: Error inflating class fragment
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763) ~[na:0.0]
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) ~[na:0.0]
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) ~[na:0.0]
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) ~[na:0.0]
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504) ~[na:0.0]
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414) ~[na:0.0]
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365) ~[na:0.0]
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source) ~[na:0.0]
	at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.MainActivity.onCreate(Unknown Source) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:6020) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284) ~[na:0.0]
	... 10 common frames omitted
Caused by: android.database.sqlite.SQLiteException: near "INSERT": syntax error (code 1): , while compiling: DELETE FROM filter_lists
INSERT INTO filter_lists (filter_list_id, filter_name, filter_description, enabled, version, time_last_downloaded, time_updated, display_order) VALUES (2, 'English Filter', 'EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.', 0, '2.0.3.10', 1521504161000, 1521504161000, 1)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:897) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:508) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726) ~[na:0.0]
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58) ~[na:0.0]
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31) ~[na:0.0]
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1784) ~[na:0.0]
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1715) ~[na:0.0]
	at com.adguard.android.d.c.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.d.c.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.d.c.onUpgrade(Unknown Source) ~[na:0.0]
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256) ~[na:0.0]
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) ~[na:0.0]
	at com.adguard.android.d.c.getWritableDatabase(Unknown Source) ~[na:0.0]
	at com.adguard.android.d.c.getReadableDatabase(Unknown Source) ~[na:0.0]
	at com.adguard.android.d.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.au.<init>(Unknown Source) ~[na:0.0]
	at com.adguard.android.b.l(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.StatsFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.StatsFragment.onViewCreated(Unknown Source) ~[na:0.0]
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:875) ~[na:0.0]
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045) ~[na:0.0]
	at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1147) ~[na:0.0]
	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2116) ~[na:0.0]
	at android.app.Activity.onCreateView(Activity.java:5369) ~[na:0.0]
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentActivity.onCreateView(Unknown Source) ~[na:0.0]
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) ~[na:0.0]
	... 22 common frames omitted
```

**Comment by lancelot-moon** [comment]
Sorry that I didn't know what you reported is the same as https://github.com/AdguardTeam/AdguardForAndroid/issues/1791.

May I expect that my new Traditional Chinese translations for filters will be used in the next nightly version today? XDD

**Comment by lancelot-moon** [comment]
I tried AdGuard v2.11.67η.
**The translations for filters are all messed up!**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PVSVDsk.png)
</details><br/>

Anyway, thanks for the hard working!
Let's expect the next nightly version. :D

**Comment by lancelot-moon** [comment]
Yes, oh my God!!!
I don't know what to say. XDD

**Comment by ameshkov** [comment]
At least it does not crash anymore:)
