### ISSUE TITLE
Crash while exporting the log file

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1779]
https://github.com/AdguardTeam/AdguardFilters/issues/13014#issuecomment-373514380

2.11.31 n

"У меня есть root-права.
При попытке экспортировать лог-файлы Adguard крашится.
Но сейчас вместо рекламы показывается просто серое окно. Так и должно быть или его можно убрать?
Также прикреплю LogCat с крашем Adguard при попытке экспортировать лог-файлы."
[2018-03-15-23-31-32.txt](https://github.com/AdguardTeam/AdguardFilters/files/1817002/2018-03-15-23-31-32.txt)

**Comment by vozersky** [comment]
asked about the latest nightly

**Comment by ameshkov** [comment]
```
03-15 23:31:45.077 E/AndroidRuntime(15515): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(Unknown Source:10)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source:0)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source:10)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at com.adguard.android.ui.utils.n.a(Unknown Source:20)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at com.adguard.android.ui.utils.n.a(Unknown Source:2)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at com.adguard.android.ui.fragment.settings.SettingsAdvancedFragment$14.onClick(Unknown Source:16)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.view.View.performClick(View.java:6294)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.view.View$PerformClick.run(View.java:24770)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.os.Handler.handleCallback(Handler.java:790)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.os.Looper.loop(Looper.java:164)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at java.lang.reflect.Method.invoke(Native Method)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-15 23:31:45.077 E/AndroidRuntime(15515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): [main] Thread: Thread[main,5,main]; Uncaught exception:
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.app.Activity.startActivityForResult(Activity.java:4487) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(Unknown Source:10) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source:0) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.app.Activity.startActivityForResult(Activity.java:4445) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source:10) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at com.adguard.android.ui.utils.n.a(Unknown Source:20) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at com.adguard.android.ui.utils.n.a(Unknown Source:2) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at com.adguard.android.ui.fragment.settings.SettingsAdvancedFragment$14.onClick(Unknown Source:16) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.view.View.performClick(View.java:6294) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.view.View$PerformClick.run(View.java:24770) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.os.Handler.handleCallback(Handler.java:790) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.os.Handler.dispatchMessage(Handler.java:99) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at android.app.ActivityThread.main(ActivityThread.java:6494) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) ~[na:0.0]
03-15 23:31:45.079 E/com.adguard.android.c.d(15515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ~[na:0.0]
```

**Comment by ameshkov** [comment]
We should not crash in this case, at least show a toast message

**Comment by Revertron** [comment]
Fixed.
