### ISSUE TITLE
Error while lookup Ipv6 address on the main thread

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#1786]
```
21:38:59.233 [main] ERROR c.a.a.f.vpn.FilteringVpnService - Error building vpn interface

android.os.NetworkOnMainThreadException: null
    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1315) ~[na:0.0]
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:86) ~[na:0.0]
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74) ~[na:0.0]
    at java.net.InetAddress.getByName(InetAddress.java:708) ~[na:0.0]
    at java.net.InetSocketAddress.<init>(InetSocketAddress.java:232) ~[na:0.0]
    at com.adguard.android.filtering.b.g.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.b.g.<init>(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.b.i.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.vpn.AdguardVpnService.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.d(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.onStartCommand(Unknown Source) ~[na:0.0]
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3476) ~[na:0.0]
    at android.app.ActivityThread.-wrap23(ActivityThread.java) ~[na:0.0]
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674) ~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:105) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:156) ~[na:0.0]
    at android.app.ActivityThread.main(ActivityThread.java:6523) ~[na:0.0]
    at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) ~[na:0.0]
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) ~[na:0.0]

<!--- drag and drop, upload or paste your screenshot to this area-->
```

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Huawei Nova (HUAWEI CAZ-AL10)
* Operating system and version: 7.0
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? not

**Comment by nkartyshov** [comment]
The problem with custom DNS server setting. The user filled both DNS servers in the primary DNS server field.

Original issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/1782

**Comment by nkartyshov** [comment]
fixed
