### ISSUE TITLE
Handle "Interrupted system call" properly

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#180]
Like in this ticket: EFH-100-64229

```
21:21:21.407 [Thread-3432] ERROR c.a.a.f.vpn.FilteringVpnService - Error while reading input packet
java.io.IOException: Error Interrupted system call occurred while polling file descriptor 79
    at com.adguard.android.filtering.commons.NativeUtils.readFd(Native Method) ~[na:0.0]
    at com.adguard.android.filtering.vpn.TunDeviceImpl.read(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.serviceLoop(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.setupVpn(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.access$000(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:856) ~[na:0.0]
```

**Comment by ameshkov** [comment]
We should use the same way as with deadlocks handling.

Show "Critical Error" notification and restart protection.

**Comment by vbagirov** [comment]
Looks like similar problem: AFS-488-85017

**Comment by ameshkov** [comment]
It seems I am wrong, we should simply ignore EINTR errors:
http://stackoverflow.com/questions/1674162/how-to-handle-eintr-interrupted-system-call

**Comment by ameshkov** [comment]
In case of EINTR we should throw InterruptedIOException and then handle it in TunDeviceImpl

**Comment by ameshkov** [comment]
Done
