### ISSUE TITLE
Crash on opening app's settings with Assistant

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1833]
*Presumably* we have to use `commitAllowingStateLoss`

Adguard 2.11.81

> 15:28:50.889 [main] INFO  c.a.a.u.f.s.FirewallMainFragment - Opening package info for com.instagram.android
15:28:50.906 [main] ERROR com.adguard.android.c.d - Thread: Thread[main,5,main]; Uncaught exception:

> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(Unknown Source) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(Unknown Source) ~[na:0.0]
	at android.support.v4.app.BackStackRecord.commitInternal(Unknown Source) ~[na:0.0]
	at android.support.v4.app.BackStackRecord.commit(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.FirewallMainFragment$6.run(Unknown Source) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6692) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) ~[na:0.0]

**Comment by nkartyshov** [comment]
fixed

**Comment by nkartyshov** [comment]
**Testing instruction:** the issue is random and hard to reproduce.
