### ISSUE TITLE
AdGuard crashes when launching Assistant on Android 4.2.2

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1842]
> Помощник из панели уведомлений (шторка) не стартует. Выскакивает ошибка приложения и AG закрывается полностью.

### Steps to reproduce

1. Launch AdGuard
2. Go to the Notification menu and try to use the Assistant
3. The app crashes

### Expected behavior

User are able to launch AdGuard Assistant

### Actual behavior

Users can't operate AdGuard via Assistant due to an unexpected closure of the app

<details><summary>Logs:</summary>

https://uploads.adguard.com/np0po.txt

</details>

### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: Proxy(auto)
* Device model: Philips W8510
* Operating system and version: "4.2.2 (sdk=17)"
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by nkartyshov** [comment]
```
16:02:31.806 [main] ERROR com.adguard.android.c.d - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard.android/com.adguard.android.ui.AssistantActivity}: java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358) ~[na:0.0]
	at android.app.ActivityThread.access$600(ActivityThread.java:156) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:99) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:153) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5299) ~[na:0.0]
	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:511) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) ~[na:0.0]
	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
Caused by: java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
	at android.widget.ListView.addHeaderView(ListView.java:261) ~[na:0.0]
	at com.adguard.android.ui.AssistantActivity.onCreate(Unknown Source) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:5122) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) ~[na:0.0]
	... 11 common frames omitted
```
