### ISSUE TITLE
Check if Adguard works in Bluestacks emulator

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#188]
Source:
http://forum.xda-developers.com/android/apps-games/adguard-ad-blocker-doesnt-require-root-t2958895/post63883277#post63883277

**Comment by gshumihin** [comment]
Bluestacks restarts after enabling protection in VPN mode. With local http (auto) works fine atleast with browsers (tried chrome, firefox and built-in browser).

**Comment by gshumihin** [comment]
Ads are blocked in apps too

**Comment by ameshkov** [comment]
Great, thank you for checking it.

**Comment by ameshkov** [comment]
@gshumihin one more thing: please give a link to the exact build of bluestacks you've been using.

**Comment by gshumihin** [comment]
Downloaded version 0.9.30 for Mac os x from http://www.bluestacks.com/download.html

**Comment by gshumihin** [comment]
Here is ticket with logs: UCJ-777-64220

**Comment by ameshkov** [comment]
Does not work with 0.10.7.5601 PC version rooted. 

@gshumihin please try it.

**Comment by gshumihin** [comment]
Adguard doesn't work in bluestacks 0.10
Here is log:
```
16:31:24.122 [main] INFO  c.a.a.service.SupportServiceImpl - Updating logging levels..
16:31:24.132 [main] INFO  c.a.a.service.SupportServiceImpl - Logging levels updated successfully.
16:31:25.762 [main] DEBUG c.a.android.ui.SettingsActivity - Saved position and title!
16:31:25.932 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
16:31:28.852 [main] INFO  com.adguard.android.ui.MainActivity - Start preparing protection
16:31:28.852 [main] INFO  com.adguard.android.ui.MainActivity - No need in preparation for proxy mode
16:31:28.862 [main] INFO  com.adguard.android.ServiceManager - Handling service command. Flags=0. StartId=7
16:31:28.872 [main] INFO  com.adguard.android.ServiceManager - Starting executing command 2
16:31:28.872 [main] INFO  com.adguard.android.ServiceManager - Starting proxy protection silent
16:31:28.872 [main] INFO  c.a.a.service.ProtectionServiceImpl - Starting protection
16:31:28.872 [main] INFO  c.a.a.filtering.filter.AppFilter - Connected to network type 1
16:31:28.872 [main] INFO  c.a.a.service.ProtectionServiceImpl - Submitting StartProxyService task
16:31:28.872 [main] INFO  c.a.a.service.ProtectionServiceImpl - Submitted start protection task
16:31:28.872 [main] INFO  com.adguard.android.ServiceManager - Command 2 has been executed
16:31:28.872 [pool-3-thread-3] INFO  c.a.android.service.LongRunningTask - Start task f execution
16:31:28.872 [pool-3-thread-3] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: PREPARING
16:31:28.892 [pool-3-thread-3] INFO  c.a.a.service.WidgetServiceImpl - Updating widgets for PREPARING protection
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - Reconfiguring http filter..
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - Browsing Security status is false
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - Filtering quality status is SPEEDY
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - Firewall configuration is {"defaultPermissions":["MOBILE","WIFI"],"permissionsMap":{"com.dolphin.browser.express.web":["MOBILE","WIFI","AD_FILTERING"],"com.yandex.browser":["MOBILE","WIFI","AD_FILTERING"],"com.asus.browser":["MOBILE","WIFI","AD_FILTERING"],"com.uc.browser.en":["MOBILE","WIFI","AD_FILTERING"],"jp.ddo.pigsty.Habit_Browser":["MOBILE","WIFI","AD_FILTERING"],"com.boatgo.browser":["MOBILE","WIFI","AD_FILTERING"],"com.appdream.cloud":["MOBILE","WIFI","AD_FILTERING"],"com.baidu.browserhd.inter":["MOBILE","WIFI","AD_FILTERING"],"org.mozilla.firefox":["MOBILE","WIFI","AD_FILTERING"],"ru.yandex.shell":["MOBILE","WIFI","AD_FILTERING"],"com.cloudmosa.puffinFree":["MOBILE","WIFI","AD_FILTERING"],"com.jiubang.browser":["MOBILE","WIFI","AD_FILTERING"],"com.fevdev.nakedbrowser":["MOBILE","WIFI","AD_FILTERING"],"internetexplorer.browser.webexplorer":["MOBILE","WIFI","AD_FILTERING"],"com.nubelacorp.javelin":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.browser.id":["MOBILE","WIFI","AD_FILTERING"],"com.android.browser":["MOBILE","WIFI","AD_FILTERING"],"com.metalasfook.nochromo":["MOBILE","WIFI","AD_FILTERING"],"com.baidu.browser.inter":["MOBILE","WIFI","AD_FILTERING"],"com.opera.browser":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.browser.engine":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.web.browser.android":["MOBILE","WIFI","AD_FILTERING"],"com.fevdev.nakedbrowserpro":["MOBILE","WIFI","AD_FILTERING"],"com.UCMobile.intl":["MOBILE","WIFI","AD_FILTERING"],"cn.mozilla.firefox":["MOBILE","WIFI","AD_FILTERING"],"com.sec.android.app.sbrowser":["MOBILE","WIFI","AD_FILTERING"],"com.droid.browser":["MOBILE","WIFI","AD_FILTERING"],"com.boatbrowser.license.key":["MOBILE","WIFI","AD_FILTERING"],"me.android.browser":["MOBILE","WIFI","AD_FILTERING"],"com.opera.browser.beta":["MOBILE","WIFI","AD_FILTERING"],"com.swe.atego.browser":["MOBILE","WIFI","AD_FILTERING"],"com.rocket.browser":["MOBILE","WIFI","AD_FILTERING"],"com.uc.browser.hd":["MOBILE","WIFI","AD_FILTERING"],"com.ninesky.browser":["MOBILE","WIFI","AD_FILTERING"],"jp.ddo.pigsty.HabitBrowser":["MOBILE","WIFI","AD_FILTERING"],"acr.browser.lightning":["MOBILE","WIFI","AD_FILTERING"],"com.tencent.ibibo.mtt":["MOBILE","WIFI","AD_FILTERING"],"mobi.browser.flfoxpro":["MOBILE","WIFI","AD_FILTERING"],"com.opera.mini.android.yandex":["MOBILE","WIFI","AD_FILTERING"],"com.chrome.dev":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.browser.zero":["MOBILE","WIFI","AD_FILTERING"],"com.amazon.cloud9":["MOBILE","WIFI","AD_FILTERING"],"com.opera.browser.yandex":["MOBILE","WIFI","AD_FILTERING"],"com.ghostery.android.ghostery":["MOBILE","WIFI","AD_FILTERING"],"explore.web.browser":["MOBILE","WIFI","AD_FILTERING"],"com.ilegendsoft.mercury":["MOBILE","WIFI","AD_FILTERING"],"com.cloudmosa.puffin":["MOBILE","WIFI","AD_FILTERING"],"org.mozilla.firefox_beta":["MOBILE","WIFI","AD_FILTERING"],"com.chrome.beta":["MOBILE","WIFI","AD_FILTERING"],"ru.mail.amigo":["MOBILE","WIFI","AD_FILTERING"],"org.tint":["MOBILE","WIFI","AD_FILTERING"],"com.opera.mini.android":["MOBILE","WIFI","AD_FILTERING"],"com.explore.web.browser":["MOBILE","WIFI","AD_FILTERING"],"acr.browser.barebones":["MOBILE","WIFI","AD_FILTERING"],"com.mx.browser":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.browser":["MOBILE","WIFI","AD_FILTERING"],"mobi.browser.flashfox":["MOBILE","WIFI","AD_FILTERING"],"nextapp.atlas":["MOBILE","WIFI","AD_FILTERING"],"com.cleanmaster.security":["MOBILE","WIFI","AD_FILTERING"],"com.boatbrowser.tablet":["MOBILE","WIFI","AD_FILTERING"],"com.boatbrowser.free":["MOBILE","WIFI","AD_FILTERING"],"mobi.mgeek.TunnyBrowser":["MOBILE","WIFI","AD_FILTERING"],"com.UCMobile.intl.x86":["MOBILE","WIFI","AD_FILTERING"],"com.opera.browser.classic":["MOBILE","WIFI","AD_FILTERING"],"org.easyweb.browser":["MOBILE","WIFI","AD_FILTERING"],"com.mx.browser.tablet":["MOBILE","WIFI","AD_FILTERING"],"com.jbak.superbrowser":["MOBILE","WIFI","AD_FILTERING"],"org.adblockplus.browser":["MOBILE","WIFI","AD_FILTERING"],"com.android.chrome":["MOBILE","WIFI","AD_FILTERING"],"net.fast.web.browser":["MOBILE","WIFI","AD_FILTERING"],"com.htc.sense.browser":["MOBILE","WIFI","AD_FILTERING"],"com.dolphin.browser.android.elex":["MOBILE","WIFI","AD_FILTERING"],"nu.tommie.inbrowser":["MOBILE","WIFI","AD_FILTERING"],"com.vionika.firephoenix":["MOBILE","WIFI","AD_FILTERING"],"com.yandex.browser.beta":["MOBILE","WIFI","AD_FILTERING"],"com.ksmobile.cb":["MOBILE","WIFI","AD_FILTERING"]},"firewallEnabled":true,"notifyForegroundAppBlocked":true,"filterAppsTraffic":false,"version":0}
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - DNS filtering status is {0}
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.filtering.filter.HttpFilter - HttpFilter reconfiguring..
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.f.firewall.FirewallFilterImpl - Applied FirewallFilterImpl configuration: 76 permission settings. Default permissions mask is MOBILE | WIFI
16:31:28.902 [pool-3-thread-3] INFO  c.a.f.filters.SafebrowsingFilter - Clearing browsing security cache
16:31:28.902 [pool-3-thread-3] INFO  c.a.f.filters.SafebrowsingFilter - Browsing security cache has been cleared
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.filtering.filter.HttpFilter - HttpFilter reconfigured successfully.
16:31:28.902 [pool-3-thread-3] INFO  c.a.a.service.ProtectionServiceImpl - Http filter reconfigured.
16:31:28.902 [pool-3-thread-3] INFO  c.a.android.proxy.HttpProxyService - Starting proxy service..
16:31:28.902 [pool-3-thread-3] INFO  c.a.android.service.LongRunningTask - Finished task f execution
16:31:28.902 [pool-3-thread-4] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: STARTING
16:31:28.922 [pool-3-thread-4] INFO  c.a.a.service.WidgetServiceImpl - Updating widgets for STARTING protection
16:31:28.922 [pool-3-thread-4] INFO  c.a.a.p.ProxyConfigurationServiceImpl - Got app proxy config: host=127.0.0.1 port=8080 transparent
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Creating server listening to /127.0.0.1:46163
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Server has been created successfully
16:31:28.922 [pool-3-thread-4] INFO  c.a.f.proxy.BaseHttpProxyServer - HTTP proxy server has been created successfully. Request statistics: false.
16:31:28.922 [pool-3-thread-4] INFO  c.a.f.proxy.BaseHttpProxyServer - Listening to /127.0.0.1:46163
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Starting tcp server
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Starting tcp listening thread
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Tcp listening thread has been started
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Tcp server has been started
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Creating server listening to /127.0.0.1:51910
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Server has been created successfully
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Starting tcp server
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Starting tcp listening thread
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Tcp listening thread has been started
16:31:28.922 [pool-3-thread-4] INFO  c.a.filter.network.TcpListener - Tcp server has been started
16:31:28.922 [pool-3-thread-4] INFO  c.a.a.p.ProxyConfigurationServiceImpl - Setting up transparent proxy.
16:31:28.962 [pool-3-thread-4] WARN  c.a.a.p.ProxyConfigurationServiceImpl - Incompatible iptables executable. Version command output: iptables v1.4.11.1
iptables v1.4.11.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
16:31:29.242 [pool-3-thread-4] WARN  c.a.a.p.ProxyConfigurationServiceImpl - Incompatible iptables executable. Version command output: iptables v1.4.11.1
iptables v1.4.11.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
16:31:29.242 [pool-3-thread-4] ERROR c.a.a.p.ProxyConfigurationServiceImpl - Incompatible iptables executable.
16:31:29.242 [pool-3-thread-4] ERROR c.a.a.p.ProxyConfigurationServiceImpl - Installing proxy configuration failed
java.io.FileNotFoundException: Incompatible iptables executable
	at com.adguard.android.proxy.ProxyConfigurationServiceImpl.initIpTables(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.ProxyConfigurationServiceImpl.getIpTablesPath(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.ProxyConfigurationServiceImpl.setupTransparentProxy(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService.setupTransparentProxy(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService.startService(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService.access$000(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService$1.execute(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.a.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
16:31:29.252 [pool-3-thread-4] ERROR c.a.android.proxy.HttpProxyService - Error applying proxy settings
java.io.IOException: Installing proxy configuration failed
	at com.adguard.android.proxy.HttpProxyService.setupTransparentProxy(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService.startService(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService.access$000(Unknown Source) ~[na:0.0]
	at com.adguard.android.proxy.HttpProxyService$1.execute(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.a.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
16:31:29.252 [pool-3-thread-4] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: PROXY_CONFIG_ERROR
16:31:29.272 [pool-3-thread-4] INFO  c.a.a.service.WidgetServiceImpl - Updating widgets for PROXY_CONFIG_ERROR protection
16:31:29.732 [pool-2-thread-1] DEBUG c.a.a.service.StatisticsServiceImpl - Flushing statistics data
16:31:33.802 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
16:31:44.212 [main] INFO  com.adguard.android.ServiceManager - Trim memory 20 called
```

**Comment by gshumihin** [comment]
We've found a way to filter bluestacks using Adguard for Windows:
1. Add process HD-Network to list of filtered apps (filtered apps -> add application -> browse for executable -> add file C:\\Program Files (x86)\BlueStacks\HD-Network.exe
[img src="https://www.dropbox.com/s/81h0yn7jz5w7rxd/add_app.png" width=200 /img]
2. You'll need to add adguard certificate to bluestacks.

**Comment by ameshkov** [comment]
Great!

**Comment by ameshkov** [comment]
@gshumihin seems there's an issue with Bluestacks 2.0.2:
http://forum.adguard.com/showthread.php?8373-Adguard-%D0%B4%D0%BB%D1%8F-Windows-%D0%A0%D0%B5%D0%BB%D0%B8%D0%B7-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82-Adguard-6-0&p=71072&viewfull=1#post71072

Please check it.
