### ISSUE TITLE
Nightly crashes on flight mode switching

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#1902]
```06-06 21:23:19.281  4886  8951 E AndroidRuntime: FATAL EXCEPTION: tcpip-stack-pool-1-thread-169
06-06 21:23:19.281  4886  8951 E AndroidRuntime: Process: com.adguard.android, PID: 4886
06-06 21:23:19.281  4886  8951 E AndroidRuntime: java.lang.IllegalStateException: This TCP/IP stack instance is closed
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.checkOpen(Unknown Source)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.completeTcpConnectRequest(Unknown Source)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.access$200(Unknown Source)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl$Callbacks$1.run(Unknown Source)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-06 21:23:19.281  4886  8951 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:760)
```
New exceptions are not handled in TCP/IP stack listener?

### Steps to reproduce

1. Turn on flight mode
2. Turn off flight mode
3. Repeat

### Expected behavior
Adguard doesn't crash

### Actual behavior
Adguard crashes

### Your environment

* Adguard version: 2.12.47
* Adguard filtering mode: VPN
* Device model: Xiaomi mi5s
* Operating system and version: Android 7.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Adguard

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/CoreLibs #320](https://github.com/AdguardTeam/CoreLibs/issues/320) via [**ZenHub**](https://www.zenhub.com/)
