### ISSUE TITLE
CursorWindowAllocationException crash

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1947]
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
    at android.database.CursorWindow.<init>(CursorWindow.java:108)
    at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
    at com.adguard.android.c.b.a(AppRulesDaoImpl.java:46)
    at com.adguard.android.service.e.a(AppRulesServiceImpl.java:193)
    at com.adguard.android.service.e.a(AppRulesServiceImpl.java:140)
    at com.adguard.android.service.e.a(AppRulesServiceImpl.java:120)
    at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(FirewallMainFragment.java:1303)
    at com.adguard.android.ui.fragment.settings.FirewallMainFragment.a(FirewallMainFragment.java:63)
    at com.adguard.android.ui.fragment.settings.FirewallMainFragment$8.run(FirewallMainFragment.java:510)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by ameshkov** [comment]
Most likely something is wrong with the device state -- low memory for instance.
