### ISSUE TITLE
Error while importing settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1955]
```
java.lang.RuntimeException: Unable to import null to preferences!
    at com.adguard.android.service.SettingsBackupServiceImpl.putPref(SettingsBackupServiceImpl.java:344)
    at com.adguard.android.service.SettingsBackupServiceImpl.importSettings(SettingsBackupServiceImpl.java:121)
    at com.adguard.android.service.SettingsBackupServiceImpl.importSettings(SettingsBackupServiceImpl.java:179)
    at com.adguard.android.service.SettingsBackupServiceImpl.importSettings(SettingsBackupServiceImpl.java:195)
    at com.adguard.android.ui.fragment.settings.SettingsGeneralFragment$ImportTask.run(SettingsGeneralFragment.java:559)
    at com.adguard.android.ui.fragment.settings.SettingsGeneralFragment$ImportExportTask.doInBackground(SettingsGeneralFragment.java:608)
    at com.adguard.android.ui.fragment.settings.SettingsGeneralFragment$ImportExportTask.doInBackground(SettingsGeneralFragment.java:584)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:300)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

**Comment by admitrevskiy** [comment]
Resolved.

Steps to reproduce: 
-This bug was observable on devices older than KitKat without activated license.
-Go to `Settings -> General` 
-Export settings
-Try to import settings back

Testing instructions: 
-Reinstall AG
-Repeat above-stated steps

Expected results:
-Settings should be imported successfully
