### ISSUE TITLE
Crash: The specified child already has a parent

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1956]
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:4919)
    at android.view.ViewGroup.addView(ViewGroup.java:4750)
    at android.view.ViewGroup.addView(ViewGroup.java:4690)
    at android.view.ViewGroup.addView(ViewGroup.java:4663)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1434)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
    at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:855)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2593)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:854)
    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:797)
    at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:186)
    at com.adguard.android.ui.BaseActivity.onBackPressed(BaseActivity.java:115)
    at com.adguard.android.ui.FirewallActivity.onBackPressed(FirewallActivity.java:160)
    at android.app.Activity.onKeyUp(Activity.java:2988)
    at com.adguard.android.ui.BaseActivity.onKeyUp(BaseActivity.java:283)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
    at android.app.Activity.dispatchKeyEvent(Activity.java:3280)
    at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4768)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4640)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4228)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4194)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4321)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4202)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4378)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4228)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4194)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4202)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4228)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4194)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4354)
    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4515)
    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2465)
    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2028)
    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2019)
    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2442)
    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:325)
    at android.os.Looper.loop(Looper.java:142)
    at android.app.ActivityThread.main(ActivityThread.java:6798)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by admitrevskiy** [comment]
Resolved

Testing instructions:
-This crash was caused by rapid change between `Apps Management ` and `App Details` screens. Try to reproduce it before reinstalling AG and testing this fix.
