### ISSUE TITLE
IllegalArgumentException: No view found for id 0x7f0f00f7 (com.adguard.android:id/fragment_container) for fragment SslWhitelistFragment

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1979]
Crash report:

```
java.lang.IllegalArgumentException: No view found for id 0x7f0f00f7 (com.adguard.android:id/fragment_container) for fragment SslWhitelistFragment{5e91e1a #14 id=0x7f0f00f7}
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5728)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions: 
-Reinstall AG
-Try to open SslWhite/Black List on tablet
