### ISSUE TITLE
Error while importing settings on Nexux 6p

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1994]
```
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1042, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/fff/adguard_settings_2.12.120_2407_1755.json flg=0x43 }} to activity {com.adguard.android/com.adguard.android.ui.SettingsActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/fff/adguard_settings_2.12.120_2407_1755.json"
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268) ~[na:0.0]
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) ~[na:0.0]
	at android.app.ActivityThread.-wrap19(Unknown Source:0) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6494) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ~[na:0.0]
Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/fff/adguard_settings_2.12.120_2407_1755.json"
	at java.lang.Long.parseLong(Long.java:590) ~[na:0.0]
	at java.lang.Long.valueOf(Long.java:804) ~[na:0.0]
	at com.adguard.android.b.f.b(ContentResolverUtils.java:40) ~[na:0.0]
	at com.adguard.android.b.f.a(ContentResolverUtils.java:79) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.SettingsGeneralFragment.onActivityResult(SettingsGeneralFragment.java:1308) ~[na:0.0]
	at com.adguard.android.ui.SettingsActivity.onActivityResult(SettingsActivity.java:171) ~[na:0.0]
	at android.app.Activity.dispatchActivityResult(Activity.java:7266) ~[na:0.0]
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264) ~[na:0.0] 
```

**Comment by admitrevskiy** [comment]
Resolved.
