### ISSUE TITLE
NRE in the OutboundProxyListFragment

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2022]
Details:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6992/?query=is:unresolved

Also this seems to be the same issue:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6992/?query=is:unresolved

```
09:40:05.460 [main] ERROR com.adguard.android.b.g - Thread: Thread[main,5,main]; Uncaught exception:  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference 	at android.view.LayoutInflater.from(LayoutInflater.java:232) ~[na:0.0] 	at com.adguard.android.ui.fragment.settings.OutboundProxyListFragment.b(OutboundProxyListFragment.java:283) ~[na:0.0] 	at com.adguard.android.ui.fragment.settings.OutboundProxyListFragment.a(OutboundProxyListFragment.java:69) ~[na:0.0] 	at com.adguard.android.ui.fragment.settings.OutboundProxyListFragment$9.onClick(OutboundProxyListFragment.java:449) ~[na:0.0] 	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166) ~[na:0.0] 	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0] 	at android.os.Looper.loop(Looper.java:154) ~[na:0.0] 	at android.app.ActivityThread.main(ActivityThread.java:6119) ~[na:0.0] 	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) ~[na:0.0] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) ~[na:0.0]
```

**Comment by admitrevskiy** [comment]
Resolved.

Steps to reproduce: 
-Go to outbound proxy settings
-Open "Add new proxy" dialog
-Change screen orientation
-Click "Save"

Testing instructions:
-Reinstall AG
-Try to reproduce

Expected behavior:
Dialog will be closed on screen rotation
