### ISSUE TITLE
2.12.140 beta net error name not resolved

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#2024]
New adg for android via DNS blocking traffic in internal Facebook app web browser. Online radio box does not play stream when app is scanning via adguard too.

Android 7.0 @ Galaxy J5 2017. 
[adguard_logs_2.12.140_0108_1401.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2249358/adguard_logs_2.12.140_0108_1401.zip)

**Comment by vozersky** [comment]
> 12:48:08.527 [cached-pool-1-thread-385] ERROR com.adguard.android.filtering.b.m - DNS id=10003763 Error while processing a DNS message

> java.net.SocketException: Network is unreachable
    at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[na:0.0]
    at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:538) ~[na:0.0]
    at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:515) ~[na:0.0]
    at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:479) ~[na:0.0]
    at sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:163) ~[na:0.0]
    at com.adguard.android.filtering.b.l.b(DnsUpstream.java:154) ~[na:0.0]
    at com.adguard.android.filtering.b.l.a(DnsUpstream.java:105) ~[na:0.0]
    at com.adguard.android.filtering.b.m.a(FilteringDnsProxyServer.java:1246) ~[na:0.0]
    at com.adguard.android.filtering.b.m$2.run(FilteringDnsProxyServer.java:216) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:762) ~[na:0.0]

> Interface: rmnet0 (rmnet0)  mtu=1500 isUp=true addresses=/2a00:f41:28c3:cd53:8504:c283:5c29:46d7/64 [null]; /fe80::50:7cb6:c001%rmnet0/64 [null]

**Comment by vozersky** [comment]
Could this be a network related issue?

**Comment by Revertron** [comment]
@vozersky Yep, only network issue :(

**Comment by FadeMind** [comment]
Page is loaded fine but after sec. I see warn. about DNS in internal facebook browser. When adguard is disabled for Facebook app then internal browser works fine. With ads ofc. This issue is only with Facebook. In Gmail pages are fine.

**Comment by ameshkov** [comment]
Guys, maybe the problem is that the Facebook app warns about domains which are blocked by AdGuard (they look like unresolved to it)?

**Comment by FadeMind** [comment]
Update. New Facebook app using Chrome browser. Issue was gone. Last thing is note working stream in Online Radio Box app when adguard scanning traffic. When adguard does not scanning app then stream is played whell.

**Comment by ameshkov** [comment]
This one?
http://onlineradiobox.com/android

**Comment by FadeMind** [comment]
@ameshkov yes.
