### ISSUE TITLE
IllegalStateException in SimpleBaseActivity

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2052]
1) IllegalStateException in SimpleBaseActivity
IllegalStateException: Only fullscreen activities can request orientation

`Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1904)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6194)
        at android.app.Activity.setRequestedOrientation(Activity.java:5831)
        at com.adguard.android.ui.utils.ActivityUtils.setForcedPortraitOnly(ActivityUtils.java:245)
        at com.adguard.newgen.ui.SimpleBaseActivity.onCreate(SimpleBaseActivity.java:21)
        at com.adguard.newgen.ui.FilteringLogActivity.onCreate(FilteringLogActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) `

It occurs on Android O+ when we try to set portrait only orientation

2) `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard3/com.adguard.newgen.ui.AppsManagementPackageActivity}: android.view.InflateException: Binary XML file line #96: Binary XML file line #96: Error inflating class <unknown>`

-DrawerActivity
-SimpleBaseActivity

**Comment by Revertron** [comment]
Fixed.
