### ISSUE TITLE
Crash: Attempt to invoke virtual method 'android.content.Context android.app.ProgressDialog.getContext()' on a null object reference

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2096]
https://sentry.adguard.com/adg/adguard-android-rs/issues/7057/events/405527/

The cause of it is this:
```
java.lang.IllegalStateException: Not allowed to start service Intent { act=Start cmp=com.adguard.android/.filtering.api.LocalVpnService (has extras) }: app is in background uid UidRecord{84ce8bd u0a369 CEM  idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577) ~[na:0.0]
	at android.app.ContextImpl.startService(ContextImpl.java:1532) ~[na:0.0]
	at android.content.ContextWrapper.startService(ContextWrapper.java:664) ~[na:0.0]
	at com.adguard.android.filtering.api.LocalVpnService.a(LocalVpnService.java:316) ~[na:0.0]
	at com.adguard.android.filtering.api.i.a(ProtectionManager.java:380) ~[na:0.0]
	at com.adguard.android.filtering.api.i.a(ProtectionManager.java:2358) ~[na:0.0]
	at com.adguard.android.service.ah.a(ProtectionServiceImpl.java:726) ~[na:0.0]
	at com.adguard.android.service.y.b(LongRunningTask.java:61) ~[na:0.0]
	at com.adguard.android.service.y.a(LongRunningTask.java:21) ~[na:0.0]
	at com.adguard.android.service.y$1.run(LongRunningTask.java:77) ~[na:0.0]
	at com.adguard.commons.concurrent.d$1.call(ThreadUtils.java:81) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/686`.

## Test instructions:
Verify that the app starts on device boot properly on Android 9.
