### ISSUE TITLE
Cannot parse power profile properly on HTC U11

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2129]
```
00:38:45.704 [main] INFO  com.adguard.android.service.a.g - Initializing PowerProfileProxyServiceXmlImpl
00:38:45.707 [main] INFO  com.adguard.android.service.a.g - Exception while parsing xml 

org.xmlpull.v1.XmlPullParserException: Exception while type casting screen.brightness
	at com.adguard.android.service.a.g.a(PowerProfileProxyServiceXmlImpl.java:178) ~[na:0.0]
	at com.adguard.android.service.a.g.a(PowerProfileProxyServiceXmlImpl.java:143) ~[na:0.0]
	at com.adguard.android.service.a.g.<init>(PowerProfileProxyServiceXmlImpl.java:51) ~[na:0.0]
	at com.adguard.android.c.a(ServiceLocator.java:398) ~[na:0.0]
	at com.adguard.android.service.a.c.<init>(BatteryServiceImpl.java:97) ~[na:0.0]
	at com.adguard.android.c.x(ServiceLocator.java:386) ~[na:0.0]
	at com.adguard.android.AdguardApplication.onCreate(AdguardApplication.java:105) ~[na:0.0]
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1132) ~[na:0.0]
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6135) ~[na:0.0]
	at android.app.ActivityThread.-wrap1(Unknown Source:0) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:105) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:180) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6950) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Resolved in `pull-requests/716`

No need to test on our side.
