### ISSUE TITLE
"No suitable constructor found for type" exception while activating the license key

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2134]
An error occurred while activating a license.

Customers:

* 2000516
* 2000594
* 2000854
* 2000052

```
org.codehaus.jackson.map.JsonMappingException: No suitable constructor found for type [simple type, class com.adguard.android.model.SubscriptionStatusResponse]: can not instantiate from JSON object (need to add/enable type information?)
 at [Source: java.io.StringReader@30c7c5e; line: 1, column: 146] (through reference chain: com.adguard.android.model.f["subscriptionStatus"])
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:746) ~[na:0.0]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683) ~[na:0.0]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[na:0.0]
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[na:0.0]
	at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579) ~[na:0.0]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697) ~[na:0.0]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[na:0.0]
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732) ~[na:0.0]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863) ~[na:0.0]
	at com.adguard.android.a.b.a(ServiceApiClient.java:235) ~[na:0.0]
	at com.adguard.android.service.i.a(ApplicationServiceImpl.java:189) ~[na:0.0]
	at com.adguard.android.service.license.b.a(AdguardLicenseServiceImpl.java:185) ~[na:0.0]
	at com.adguard.android.service.y.run(LongRunningTask.java:1059) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/723`

## Testing instructions for QA

1. Acquire a license key with an active subscription
2. Activate AdGuard with this license key
3. Expected: successful activation

Another test:

1. Cancel the subscription
2. Activate AdGuard with it again
3. Expected: successful activation
