### ISSUE TITLE
java.util.zip.DataFormatException while sending feedback

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#224]
```
18:47:57.960 [pool-2-thread-33] INFO  c.a.android.api.ServiceApiClient - Sending feedback. Body length is 3900862
18:47:58.988 [pool-2-thread-33] ERROR com.adguard.commons.web.UrlUtils - Error posting request to http://mobile.adtidy.org/api/1.0/feedback.html?key=4DDBE80A3DA94D819A00523252FB6380, post data length=3900862

java.util.zip.DataFormatException: stream error
	at java.util.zip.Deflater.deflateImpl(Native Method) ~[na:0.0]
	at java.util.zip.Deflater.deflateImpl(Deflater.java:241) ~[na:0.0]
	at java.util.zip.Deflater.deflate(Deflater.java:232) ~[na:0.0]
	at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:193) ~[na:0.0]
	at com.adguard.commons.web.UrlUtils.postRequest(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.api.HttpServiceClient.postData(Unknown Source) ~[na:0.0]
	at com.adguard.android.api.ServiceApiClient.sendFeedbackMessage(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.SupportServiceImpl.sendFeedbackMessage(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.SupportServiceImpl.access$000(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.j.processTask(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.LongRunningTask.execute(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.a.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fix:
http://static.adguard.com/android/release/adguard_issue224.apk

**Comment by TPS** [comment]
This is a big 1 for all of us beta folk — could it be pushed out automatically directly & via Amazon?

**Comment by ameshkov** [comment]
We'll push next beta in 2 days. Yet that issue seems to depend on Android version (at least it's good on 6.0).
