### ISSUE TITLE
Assistant crashes in the dev build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2260]
### Steps to reproduce

1. Try opening Assistant via the notification menu
2. The app crashes

```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard.android/com.adguard.android.ui.AssistantActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class TextView
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f010055 a=3}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
        at android.widget.TextView.<init>(TextView.java:1550)
        at android.widget.TextView.<init>(TextView.java:1129)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.adguard.android.ui.AssistantActivity.onCreate(AssistantActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Revertron** [comment]
Fixed.

**Comment by lancelot-moon** [comment]
1. In AG v3.0.109η, AG will crash if tapping AG Assistant in "long press app shortcuts".
2. There is no the warning about AG Assistant if disabling filtering log.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Reinstall AG

1) -Open app shortcuts
-Open Assistant

Expected result
-AG shouldn't crash

2) -Go to the Filtering Log
-Try to disable it

Expected result:
-Alert dialog with warning about AG Assistant appears
-"Ok" disabled filtering log
-"Cancel" do nothing (Filtering Log is still enabled)
