### ISSUE TITLE
App are crashing when search in App management

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#2508]
### Steps to reproduce
1. Open Apps management
2. Try to search apps

### Expected behavior
Search apps works

### Actual behavior
Apps crash

<details><summary>Stacktrace:</summary>
2019-02-01 09:51:10.006 18186-18186/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adguard.android, PID: 18186
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.adguard.android.ui.utils.c.a(AppsManagementUtils.java:131)
        at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:4392)
        at com.adguard.android.ui.AppsManagementMainActivity$2.run(AppsManagementMainActivity.java:496)
        at android.app.Activity.runOnUiThread(Activity.java:6507)
        at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:484)
        at com.adguard.android.ui.AppsManagementMainActivity.e(AppsManagementMainActivity.java:539)
        at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:365)
        at com.adguard.android.ui.AppsManagementMainActivity$10.onQueryTextChange(AppsManagementMainActivity.java:297)
        at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
        at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9609)
        at android.widget.TextView.handleTextChanged(TextView.java:9696)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12284)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1256)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:848)
        at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:621)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:399)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
</details>

### Your environment
* Adguard version: 3.0.217
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by nkartyshov** [comment]
fixed

**Comment by Nzzyme** [comment]
Seeing this bug in 3.0.217 too
