### ISSUE TITLE
ClassCastException in SettingsDangerousFragment

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2909]
Crash from Sentry: 
https://sentry.adguard.com/adg/adguard-android-rs/issues/14614/?query=is:unresolved%20ClassCastException

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:310) ~[na:0.0]
	at com.adguard.android.service.y.c(AdvancedPreferencesServiceImpl.java:3) ~[na:0.0]
        ....
```

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
*To reproduce this issue repeat the following steps*:
- Install nightly version from v3.1.77 to v3.1.86
- Export settings
- Import settings
- Go to `Settings -> Advanced -> Low level Settings`
- AG will crash
- Try to enable DNS filtering and protection
- AG will not start the protection

*To check the bugfix*:
- Reinstall AG
- Try to reproduce the steps
