### ISSUE TITLE
Error while checking updates of userscripts added from the local storage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2997]
```
00:58:43.542 [pool-1-thread-2] WARN  c.a.c.p.u.UserscriptManager - Error downloading userscript: content://com.android.externalstorage.documents/document/primary%3ARuTor.org%20Search%20Filter.js
java.net.MalformedURLException: unknown protocol: content
	at java.net.URL.<init>(URL.java:597) ~[na:0.0]
	at java.net.URL.<init>(URL.java:487) ~[na:0.0]
	at java.net.URL.<init>(URL.java:436) ~[na:0.0]
	at com.adguard.corelibs.proxy.userscript.UserscriptManager.download(UserscriptManager.java:1) ~[na:0.0]
	at com.adguard.corelibs.proxy.userscript.UserscriptManager.isUpdateAvailable0(Native Method) ~[na:0.0]
	at com.adguard.corelibs.proxy.userscript.UserscriptManager.isUpdateAvailable(UserscriptManager.java:2) ~[na:0.0]
	at com.adguard.android.service.a.c.a(UserscriptsServiceImpl.java:18) ~[na:0.0]
	at com.adguard.android.service.job.l$e.a(JobFactoryImpl.java:2) ~[na:0.0]
	at com.adguard.android.service.job.e.run(Unknown Source:2) ~[na:0.0]
	at com.adguard.android.service.job.i.run(AbstractJob.java:2) ~[na:0.0]
	at com.adguard.android.service.job.l$e.run(JobFactoryImpl.java:1) ~[na:0.0]
	at com.adguard.android.service.job.Worker.doWork(Worker.java:10) ~[na:0.0]
	at androidx.work.Worker$1.run(Worker.java:1) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by Chinaski1** [comment]
The same problem occurs on Custom filters

<details><summary>Screenshot:</summary>

>
![image](https://user-images.githubusercontent.com/49645813/65879698-0ed74080-e399-11e9-9369-d71d8052f003.png)


</details>

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Add Extension/Custom filter/DNS Filter from local storage
- Go to Main screen
- Tap on `Update`

Expected result:
- No errors on update attempt.
