### ISSUE TITLE
AdGuard fails to start protection after an update

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3024]
### Issue Details

AdGuard hangs on "Preparing to start protection" screen after updating to 3.2.
 
- **AdGuard version:**
  - 3.2.135r, 3.2.139n
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Mi Max 2
- **Operating system and version:**
  - Android 7.1.1
- **Root access:**
  - No

### Expected Behavior

Protection should start without issues after an update

### Actual Behavior

AdGuard hangs on "Preparing to start protection..." screen after updating to 3.2.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2019-08-21-10-50-06-686_com adguard android](https://user-images.githubusercontent.com/33634917/63650825-880ac480-c757-11e9-8282-90b835ca5029.png)

</details>

### Additional Information

Attempted steps:
 * Battery / task killer optimization;
 * Moving to Nightly.

Support ticket ID: 1073595

**Comment by ameshkov** [comment]
Error from the log:
```
11:14:56.110 [protection-pool-3-thread-2] WARN  com.adguard.android.service.U - An error occurred on StartProtection task execution:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.adguard.corelibs.network.OutboundProxyConfig com.adguard.android.filtering.proxy.a.toProxyServerConfig()' on a null object reference
	at com.adguard.android.d.a.d.<init>(CoreProxyServerImpl.java:64) ~[na:0.0]
	at com.adguard.android.filtering.api.k$a.d(ProtectionManager.java:10) ~[na:0.0]
	at com.adguard.android.filtering.api.k$a.b(ProtectionManager.java:8) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl$c.a(ProtectionServiceImpl.java:17) ~[na:0.0]
	at com.adguard.android.service.U.b(LongRunningTask.java:1) ~[na:0.0]
	at com.adguard.android.service.U.run(LongRunningTask.java:4) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:760) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@akmLaVx ask the user to disable proxy: settings - network - proxy - disable it

**Comment by Varolyt** [comment]
@ameshkov помогло, спасибо

**Comment by ameshkov** [comment]
@Varolyt отлично, спасибо что подтвердили

**Comment by ameshkov** [comment]
Fixed in `pull-requests/1433`
