### ISSUE TITLE
AdGuard 3.3.5 crashes when exporting setting, creates empty file

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3060]
### Issue Details

- **AdGuard version:**
  - 3.3.5
- **Filtering mode:**
  - VPN
- **Device:**
  - Samsung SM-T555
- **Operating system and version:**
  - 7.1.1
- **Root access:**
  - n/a

### Expected Behavior

AdGuard does not crash

### Actual Behavior

It crashes during the process of exporting

### Additional Information

For logs, please check this ticket: 1394429

**Comment by SergeiShir** [comment]
I experience the same issue
Nightly app version: 3.3.14, corelibs version: 1.4.138
I enabled Debug=Everything
Below is an excerpt from the log


07:11:56.647 [single-pool-3-thread-1] INFO  c.a.android.filtering.commons.e - Interface: rmnet_ipa0 (rmnet_ipa0)  mtu=2000 isUp=true
07:11:56.647 [single-pool-3-thread-1] INFO  c.a.a.r.NetworkStateReceiver - The connection did not really change, doing nothing
07:11:56.647 [single-pool-3-thread-1] INFO  c.a.a.r.NetworkStateReceiver - Finished handling android.net.conn.CONNECTIVITY_CHANGE asynchronously
07:12:03.149 [single-pool-3-thread-1] INFO  com.adguard.android.service.b.b - No native crash files found in /storage/emulated/0/Android/data/com.adguard.android/cache/crashes, doing nothing
07:12:04.696 [main] INFO  c.a.android.filtering.commons.d - Updating logging levels to DEBUG
07:12:04.697 [main] INFO  c.a.android.filtering.commons.d - Logging levels updated successfully.
07:12:16.355 [AsyncTask #3] DEBUG com.adguard.android.service.r - Getting CA certificate alias
07:12:16.455 [AsyncTask #3] DEBUG com.adguard.android.service.r - Checking certificate C=EN,CN=AdGuard Personal CA
07:12:16.455 [AsyncTask #3] DEBUG com.adguard.android.service.r - The AdGuard certificate is stored by alias user:88cba841.0
07:12:24.509 [debounce-battery-servicepool-3-thread-13] DEBUG c.a.a.s.battery.BatteryServiceImpl - Calculated usage: 1568088744505 18438 0 0 0 0 true
07:12:25.754 [AsyncTask #4] ERROR com.adguard.android.b.i - Thread: Thread[AsyncTask #4,5,main]; Uncaught exception:

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354) ~[na:0.0]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) ~[na:0.0]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) ~[na:0.0]
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
Caused by: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:283) ~[na:0.0]
	at com.adguard.android.model.settings.-$$Lambda$B1LvIImCrYMf_rDq_Mp-_i8JMMI.extract(Unknown Source:4) ~[na:0.0]
	at com.adguard.android.model.settings.c.a(SettingsManager.java:627) ~[na:0.0]
	at com.adguard.android.model.settings.c.a(SettingsManager.java:648) ~[na:0.0]
	at com.adguard.android.model.settings.c.a(SettingsManager.java:169) ~[na:0.0]
	at com.adguard.android.model.settings.c.a(SettingsManager.java:107) ~[na:0.0]
	at com.adguard.android.service.ai.a(SettingsBackupServiceImpl.java:123) ~[na:0.0]
	at com.adguard.android.service.ai.a(SettingsBackupServiceImpl.java:146) ~[na:0.0]
	at com.adguard.android.ui.v.a(SettingsActivity.java:316) ~[na:0.0]
	at com.adguard.android.ui.w.doInBackground(SettingsActivity.java:1348) ~[na:0.0]
	at android.os.AsyncTask$2.call(AsyncTask.java:333) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	... 4 common frames omitted
07:12:26.734 [debounce-battery-servicepool-3-thread-14] DEBUG c.a.a.s.battery.BatteryServiceImpl - Calculated usage: 1568088746731 18438 0 0 0 0 false
07:12:29.882 [AsyncTask #4] DEBUG io.sentry.event.b - Updating the hostname cache
07:12:29.900 [AsyncTask #4] DEBUG io.sentry.b.b - Adding Event to offline storage: /data/user/0/com.adguard.android/cache/sentry-buffered-events/f08923c1-20a8-4b64-972a-125fece5e834.sentry-event
07:12:29.936 [AsyncTask #4] DEBUG io.sentry.b.b - 1 stored events are now in dir: /data/user/0/com.adguard.android/cache/sentry-buffered-events
07:12:29.944 [sentry-pool-1-thread-1] WARN  io.sentry.d.a.lockdown - Initiated a temporary lockdown because of exception: An exception occurred while submitting the event to the Sentry server.
07:12:29.946 [sentry-pool-1-thread-1] ERROR io.sentry.d.b - An exception occurred while sending the event to Sentry.
io.sentry.d.i: An exception occurred while submitting the event to the Sentry server.
	at io.sentry.d.k.b(HttpConnection.java:216) ~[na:0.0]
	at io.sentry.d.a.a(AbstractConnection.java:76) ~[na:0.0]
	at io.sentry.d.e.a(BufferedConnection.java:105) ~[na:0.0]
	at io.sentry.d.c.run(AsyncConnection.java:185) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
Caused by: java.net.UnknownHostException: Unable to resolve host "sentry.adguard.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157) ~[na:0.0]
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105) ~[na:0.0]
	at java.net.InetAddress.getAllByName(InetAddress.java:1154) ~[na:0.0]
	at com.android.okhttp.Dns$1.lookup(Dns.java:39) ~[na:0.0]
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175) ~[na:0.0]
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141) ~[na:0.0]
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83) ~[na:0.0]
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174) ~[na:0.0]
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[na:0.0]
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) ~[na:0.0]
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461) ~[na:0.0]
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127) ~[na:0.0]
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) ~[na:0.0]
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26) ~[na:0.0]
	at io.sentry.d.k.b(HttpConnection.java:168) ~[na:0.0]
	... 6 common frames omitted
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method) ~[na:0.0]
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172) ~[na:0.0]
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137) ~[na:0.0]
	... 22 common frames omitted
07:12:30.538 [AsyncTask #7] DEBUG com.adguard.android.service.r - Getting CA certificate alias
07:12:30.676 [AsyncTask #7] DEBUG com.adguard.android.service.r - Checking certificate C=EN,CN=AdGuard Personal CA
07:12:30.677 [AsyncTask #7] DEBUG com.adguard.android.service.r - The AdGuard certificate is stored by alias user:88cba841.0
07:12:33.890 [main] INFO  c.a.android.filtering.commons.d - Found resource [assets/logback.xml] at [assets/logback.xml]
07:12:33.890 [main] INFO  c.a.android.filtering.commons.d - debug attribute not set
07:12:33.890 [main] INFO  c.a.android.filtering.commons.d - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
07:12:33.890 [main] INFO  c.a.android.filtering.commons.d - Naming appender as [logcat]
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Setting level of logger [com.adguard.android.filtering.io] to INFO
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Setting level of logger [com.adguard.android.filtering] to INFO
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Setting level of logger [com.adguard.android.FilteringLog] to INFO
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Setting level of ROOT logger to INFO
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Attaching appender named [logcat] to Logger[ROOT]
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - End of configuration.
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Registering current configuration as safe fallback point
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - No compression will be used
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Will use the pattern /storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.%d.log for the active file
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - The date pattern is 'yyyy-MM-dd' from file name pattern '/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.%d.log'.
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Roll-over at midnight.
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Setting initial period to Tue Sep 10 07:12:30 GMT+03:00 2019
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Active log file name: /storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - File property is set to [/storage/emulated/0/Android/data/com.adguard.android/cache/log/adguard.log]
07:12:33.891 [main] INFO  c.a.android.filtering.commons.d - Logger is configured
07:12:33.896 [main] INFO  c.a.android.AdguardApplication - Creating AdGuard application. Process name: com.adguard.android, app version: 3.3.14, corelibs version: 1.4.138
07:12:33.896 [main] INFO  c.a.android.AdguardApplication - Device information: manufacturer=Google model=Pixel 2 XL brand=google version=9 security_patch=2019-08-01

**Comment by patrickdrd** [comment]
I tried to export the settings some days ago and it crashed and
I tried again, same results..
I didn't check to see if it created an empty file, because I was disappointed,
It seems that the settings exporting is a long-lasting pain..
anyway, thank god I've got titanium backup in all my phones these days..

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG on phone with Android 7- aboard
-Change notification type in General Settings
-Add some rules to: Whitelist/UserFilter/Dns UserFilter and disable some of them
-Try to export settings

Expected result:
-No crashes
