### ISSUE TITLE
Keep track of ClosedChannelExceptions and add such hosts to SSL exceptions automatically

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#312]
Example is Skype, I see lots of errors in the log:
```
02-20 17:34:21.433   9360-26822/? E/com.adguard.filter.proxy.BaseHttpProxyServer﹕ [pool-3-thread-156] TCP id=100635 Error while processing connection. Connection info: com.skype.raider /172.16.16.1:47205 /13.75.106.0:443 10213
    java.nio.channels.ClosedChannelException: null
            at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
            at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
            at com.adguard.commons.io.SocketChannelOutputStream.write(SocketChannelOutputStream.java:46) ~[na:0.0]
            at com.adguard.commons.io.SocketChannelOutputStream.write(SocketChannelOutputStream.java:37) ~[na:0.0]
            at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:72) ~[na:0.0]
            at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
            at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Done
