### ISSUE TITLE
panic: net/http: internal error: connCount underflow

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3224]
```
16:41:42.535 [threadmanager-scheduled-pool-5-thread-1] WARN  com.adguard.android.service.c.b - GoStderr: panic: net/http: internal error: connCount underflow

goroutine 5162 [running]:
net/http.(*Transport).decConnsPerHost(0x4000230000, 0x0, 0x0, 0x400008e120, 0x5, 0x4000350100, 0x16, 0x0)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/transport.go:1334 +0x418
net/http.(*Transport).roundTrip(0x4000230000, 0x40000ee500, 0x400025c360, 0x40005066c0, 0x400032defc)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/transport.go:546 +0x544
net/http.(*Transport).RoundTrip(0x4000230000, 0x40000ee500, 0x4000230000, 0xbf6f09eb93bfb01e, 0x11846b86d27e)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/roundtrip.go:17 +0x28
net/http.send(0x40000ee300, 0x79c10fcde0, 0x4000230000, 0xbf6f09eb93bfb01e, 0x11846b86d27e, 0x79c13d5460, 0x0, 0x4000010088, 0x79c13d5460, 0x1)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/client.go:250 +0x348
net/http.(*Client).send(0x4000270480, 0x40000ee300, 0xbf6f09eb93bfb01e, 0x11846b86d27e, 0x79c13d5460, 0x4000010088, 0x0, 0x1, 0x4000470400)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/client.go:174 +0xc0
net/http.(*Client).do(0x4000270480, 0x40000ee300, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/client.go:641 +0x2c8
net/http.(*Client).Do(...)
	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/net/http/client.go:509
github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverHTTPS).exchangeHTTPSClient(0x40002700c0, 0x4000136240, 0x4000270480, 0x0, 0x0, 0x0)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/upstream/upstream_doh.go:68 +0x1e0
github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverHTTPS).Exchange(0x40002700c0, 0x4000136240, 0x79c13d5460, 0x0, 0x0)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/upstream/upstream_doh.go:42 +0x4c
github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(0x79c11002a0, 0x40002700c0, 0x4000136240, 0x0, 0x0, 0x0, 0x0)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:463 +0x54
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).exchange(0x40000e2000, 0x4000136240, 0x400034c130, 0x1, 0x1, 0x1, 0x0, 0x0, 0x4000278520, 0x10)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:423 +0x298
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0x40000e2000, 0x4000470380, 0x0, 0x0)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:378 +0xb4
github.com/AdguardTeam/dnsproxy/mobile.(*DNSProxy).handleDNSRequest(0x400008c080, 0x40000e2000, 0x4000470380, 0x7913bdb3e6, 0x79c10e33e0)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/mobile/filter.go:141 +0xf8
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x40000e2000, 0x4000470380, 0x28, 0x28)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:929 +0x19c
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(0x40000e2000, 0x400064a210, 0x28, 0x28, 0x79c1100920, 0x4000506600, 0x4000010018)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:640 +0x1a4
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x40000e2000, 0x400064a210, 0x28, 0x28, 0x79c1100920, 0x4000506600, 0x4000010018)
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:608 +0x50
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
	/home/travis/build/AdguardTeam/dnsproxy/mobile/build/src/github.com/AdguardTeam/dnsproxy/proxy/proxy.go:607 +0x348
```

Thiss appears to be a known bug of Go v1.13:
https://github.com/golang/go/issues/34941

**Comment by ameshkov** [comment]
It seems they're not going to fix this in Go v1.13.

As a temporary workaround, we can stop setting `MaxConnsPerHost`
