### ISSUE TITLE
HTTPS filtering breaks connection when ClientHello does not contain SSL extensions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#342]
```
12:18:09.456 [pool-2-thread-1766] ERROR c.a.f.proxy.BaseHttpProxyServer - TCP id=104222 Error while processing connection. Connection info: com.bbm /172.16.16.1:48935 /74.82.93.60:443 10244

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Hashtable.put(java.lang.Object, java.lang.Object)' on a null object reference
	at com.adguard.filter.proxy.ssl.SslProxyClient.getClientExtensions(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsClientProtocol.sendClientHelloMessage(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsClientProtocol.connect(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.SslProxyRemoteEndPoint.connect(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.SslMitmManager.establishConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.ssl.SslMitmManager.establishConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.BaseHttpProxyServer.acceptIncomingSslConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.BaseHttpProxyServer.acceptIncomingConnection(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.FilteringProxyServer.acceptIncomingConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener.acceptConnection(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener.access$100(Unknown Source) ~[na:0.0]
	at com.adguard.filter.network.TcpListener$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fixed
