### ISSUE TITLE
NullPointerException on registering redirected connection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#344]
```
16:51:35.880 [pool-2-thread-3061] DEBUG c.a.a.filtering.commons.LogUtils - TCP id=8278 Register redirected connection info for port 55536
16:51:35.949 [pool-2-thread-3061] DEBUG c.a.a.filtering.commons.LogUtils - TCP id=8278 Cannot connect to /104.236.175.73:443 for null
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:847) ~[na:0.0]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:842) ~[na:0.0]
	at com.adguard.android.filtering.filter.AppFilter.addRedirectedNetConnectionInfo(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.connect(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.connect(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.tcpInputClosed(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.VpnTcpConnection.addBrowserInputPacket(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.BaseVpnConnection$1.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fixed
