### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#363]
One user reports (in ticket XTJ-416-98442) that in proxy mode after some time while using Adguard it looses Internet connection. Restart of Adguard helps to regain connection.
In log file I can see many exceptions like this:

```
java.net.ConnectException: failed to connect to /104.244.43.69 (port 80): connect failed: EMFILE (Too many open files)
    at libcore.io.IoBridge.connect(IoBridge.java:124) ~[na:0.0]
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) ~[na:0.0]
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) ~[na:0.0]
    at java.net.Socket.connect(Socket.java:884) ~[na:0.0]
    at java.nio.SocketChannelImpl$SocketAdapter.connect(SocketChannelImpl.java:531) ~[na:0.0]
    at java.net.Socket.connect(Socket.java:827) ~[na:0.0]
    at com.adguard.filter.proxy.RemoteEndPoint.connect(Unknown Source) ~[na:0.0]
    at com.adguard.filter.proxy.BaseProxyConnectionContext.getRemoteEndPoint(Unknown Source) ~[na:0.0]
    at com.adguard.filter.proxy.BaseHttpProxyServer.writeHttpRequest(Unknown Source) ~[na:0.0]
    at com.adguard.filter.proxy.BaseHttpProxyServer.processHttpRequest(Unknown Source) ~[na:0.0]
    at com.adguard.filter.proxy.BaseHttpProxyServer.processConnection(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.filter.FilteringHttpProxyServer.processConnection(Unknown Source) ~[na:0.0]
    at com.adguard.filter.proxy.BaseHttpProxyServer.acceptIncomingConnection(Unknown Source) ~[na:0.0]
    at com.adguard.filter.network.TcpListener.acceptConnection(Unknown Source) ~[na:0.0]
    at com.adguard.filter.network.TcpListener.access$100(Unknown Source) ~[na:0.0]
    at com.adguard.filter.network.TcpListener$2.run(Unknown Source) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: android.system.ErrnoException: connect failed: EMFILE (Too many open files)
    at libcore.io.Posix.connect(Native Method) ~[na:0.0]
    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111) ~[na:0.0]
    at libcore.io.IoBridge.connectErrno(IoBridge.java:137) ~[na:0.0]
    at libcore.io.IoBridge.connect(IoBridge.java:122) ~[na:0.0]
    ... 18 common frames omitted
```

May be we need to implement some auto-restart of proxy, or something like that?

**Comment by Bohdan-SUP** [comment]
New log - UKJ-959-27978

**Comment by ameshkov** [comment]
@Bohdan-SUP could you please recommend user to try v2.5 beta?

**Comment by Bohdan-SUP** [comment]
It's already 2.5.123.

**Comment by TPS** [comment]
What often WFM _most_ in this case (inexplicably) is:
1. Turn off wifi.
2. Force-stop AG, & then clear cache (_not_ data!)
3. Restart AG.
4. Turn on wifi.

Is that the procedure that your reporting user is following, @Bohdan-SUP?  If not, maybe it'd help him/her while you @all hunt this down.

**Comment by ameshkov** [comment]
Why, in this particular case it's enough to turn wi-fi off/on without clearing the cache and restarting.

The problem here is with open sockets limit existing in OS. Turning wi-fi on/off you in fact close all open sockets forcibly, hence the issue is resolved.

The question is: why does he have so many open sockets? Clearly some app causes it. I'd like to know which app exactly.

**Comment by evgeniy-ADG** [comment]
another log: 1134218

**Comment by Revertron** [comment]
Log from user 1134218 shows that Adguard is killed by system, but no cause is known. It is not connected with "Too many open files".

**Comment by Revertron** [comment]
The main and only suspect is Fenix for Twitter: it.mvilla.android.fenix
