### ISSUE TITLE
Nekto Me app doesn't work

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#374]
Nekto Me
https://play.google.com/store/apps/details?id=com.nektome.talk&hl=en

При выборе всех параметров для чата и нажатии "Поиск" не происходит сам поиск собеседников и приложение сообщает, что "Собеседник не найден".
http://prntscr.com/agpk6u

Отключение фильтров не помогает.
Помогает полное отключение Адг

**Comment by ameshkov** [comment]
Помогает ли отключение фильтрации?

**Comment by Revertron** [comment]
```
TCP id=2629 Connecting to /104.28.16.28:80
TCP id=2627 Cannot connect to /104.28.16.28:80 for com.nektome.talk java.net.SocketTimeoutException: failed to connect to /104.28.16.28 (port 80) after 5000ms
            at libcore.io.IoBridge.connectErrno(IoBridge.java:169) ~[na:0.0]
            at libcore.io.IoBridge.connect(IoBridge.java:122) ~[na:0.0]
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) ~[na:0.0]
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) ~[na:0.0]
            at java.net.Socket.connect(Socket.java:882) ~[na:0.0]
            at java.nio.SocketChannelImpl$SocketAdapter.connect(SocketChannelImpl.java:531) ~[na:0.0]
            at com.adguard.android.filtering.vpn.l.c(Unknown Source) ~[na:0.0]
            at com.adguard.android.filtering.vpn.a$1.run(Unknown Source) ~[na:0.0]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```
And the same for second IP - 104.28.17.28.

**Comment by Revertron** [comment]
The app doesn't work at all now.

**Comment by ameshkov** [comment]
Confirming the issue. I don't see any other way except adding it to exceptions list.

**Comment by Alex-302** [comment]
It seems this app works with current versions.
@AdguardTeam/qa-team please check.

**Comment by zzebrum** [comment]
Seems to be working now. The app doesn't trust our cert though.
