### ISSUE TITLE
"NetworkCallback was not registered" error on stopping protection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3870]
@artemiv4nov can this occur on v3.6.x?

Please find the full logs attached to the internal JIRA issue.

Here's the important part of it:
```
com.adguard.android.service.-$$Lambda$ProtectionServiceImpl$d$RKt9rq4K0f5ygt5g_3ZJq9lFAew@11b4864 task execution:

java.lang.IllegalArgumentException: NetworkCallback was not registered
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:52)
	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4333)
	at com.adguard.android.service.ProtectionServiceImpl.m(ProtectionServiceImpl.java:41825)
	at com.adguard.android.service.ProtectionServiceImpl$d.a(ProtectionServiceImpl.java:1031)
	at com.adguard.android.service.a.b.b(LongRunningTask.java:1032)
	at com.adguard.android.service.a.a.c(AbstractLongRunningTask.java:101)
	at com.adguard.commons.concurrent.Command.run(Command.java:173)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
11:11:49.146 [protection-pool-11-thread-1] INFO  com.adguard.android.service.a.a - Finished task com.adguard.android.service.-$$Lambda$ProtectionServiceImpl$d$RKt9rq4K0f5ygt5g_3ZJq9lFAew@11b4864 execution
```

**Comment by artemiv4nov** [comment]
This is an ancient bug. It can occur while the DNS filtering is changed its state. Common stop & start should help.
