### ISSUE TITLE
Adguard crashes on certificate installation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#390]
Source report:
http://forum.adguard.com/showthread.php?9846-Adguard-for-Android-Beta-version-2-5-70&p=80201&viewfull=1#post80201

```
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): [main] Thread: Thread[main,5,main]; Uncaught exception:
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.keychain/com.android.certinstaller.CertInstallerMain}; have you declared this activity in your AndroidManifest.xml?
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1761) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.app.Activity.startActivityForResult(Activity.java:3749) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.app.Activity.startActivityForResult(Activity.java:3710) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.support.v4.app.FragmentActivity.startActivityFromFragment(Unknown Source) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.support.v4.app.Fragment.startActivity(Unknown Source) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at com.adguard.android.ui.fragment.settings.c.onPostExecute(Unknown Source) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.os.AsyncTask.finish(AsyncTask.java:632) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.os.AsyncTask.access$600(AsyncTask.java:177) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.os.Looper.loop(Looper.java:135) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at android.app.ActivityThread.main(ActivityThread.java:5221) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) ~[na:0.0]
03-25 13:39:34.763 E/com.adguard.android.commons.b(17343): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) ~[na:0.0]
```

**Comment by ameshkov** [comment]
I suppose we should catch that exception and try installing certificate through the browser.

**Comment by Revertron** [comment]
Done.
