### ISSUE TITLE
Error while sending feedback message from the app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#439]
```
00:49:40.519 [main] INFO  com.adguard.android.service.ak - Start sending feedback message task
00:49:40.581 [main] INFO  com.adguard.android.service.ak - Submitted sending feedback message task
00:49:40.581 [pool-3-thread-6556] INFO  com.adguard.android.service.s - Start task al execution
00:49:40.633 [pool-3-thread-6556] INFO  com.adguard.android.service.i - Found 4 enabled filters
00:49:40.637 [pool-3-thread-6556] INFO  com.adguard.android.service.n - Retrieving HTTPs filtering configuration
00:49:40.909 [pool-3-thread-6556] INFO  com.adguard.android.service.n - HTTPs filtering is disabled or CA certificate is not installed
00:49:40.910 [pool-3-thread-6556] WARN  com.adguard.android.service.s - Dismissing progress dialog on error:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.adguard.filter.proxy.a.j.toString()' on a null object reference
	at com.adguard.android.service.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.ak.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.al.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.service.s.a(Unknown Source) ~[na:0.0]
	at com.adguard.commons.concurrent.c.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by Revertron** [comment]
Fixed.
