### ISSUE TITLE
App crashed during the app update

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#4419]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 40

### Environment

```markdown
OS: Android 8.1/9
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to the Updates screen
2. tap to the "Update" button
3. app crashed

Well, I think we have to fix it ASAP.

### Actual Behavior

The app should be crashed when a user checks updates.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Disqu3-mirOir-qt** [comment]
FATAL EXCEPTION: main
Process: com.adguard.android, PID: 2041
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:714)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:59)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at y7.a.c(ProgressSnackWrapper.kt:1)
	at y7.a.b(ProgressSnackWrapper.kt:8)
	at y7.a.e(ProgressSnackWrapper.kt:1)
	at com.adguard.android.ui.fragment.UpdatesFragment.j0(UpdatesFragment.kt:6)
	at com.adguard.android.ui.fragment.UpdatesFragment.v(Unknown Source:0)
	at h3.g0.onChanged(Unknown Source:6)
	at m7.g.b(RealTimeLiveData.kt:1)
	at m7.g.a(Unknown Source:0)
	at m7.f.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.adguard.android:color/selector_service_view_color_secondary_dark with resource ID #0x7f050112
Caused by: android.content.res.Resources$NotFoundException: File res/color/selector_service_view_color_secondary_dark.xml from drawable resource ID #0x7f050112
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1097)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:908)
	at android.content.res.Resources.loadDrawable(Resources.java:1036)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1005)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
	at android.view.View.<init>(View.java:4746)
	at android.view.View.<init>(View.java:4647)
	at android.view.View.<init>(View.java:4626)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:714)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:59)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at y7.a.c(ProgressSnackWrapper.kt:1)
	at y7.a.b(ProgressSnackWrapper.kt:8)
	at y7.a.e(ProgressSnackWrapper.kt:1)
	at com.adguard.android.ui.fragment.UpdatesFragment.j0(UpdatesFragment.kt:6)
	at com.adguard.android.ui.fragment.UpdatesFragment.v(Unknown Source:0)
	at h3.g0.onChanged(Unknown Source:6)
	at m7.g.b(RealTimeLiveData.kt:1)
	at m7.g.a(Unknown Source:0)
	at m7.f.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable
	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:189)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:145)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1254)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1084)
	... 42 more

**Comment by Squall-Leonhart** [comment]
so it seems nobody has been able to get nightly 41.
