### ISSUE TITLE
Unexpected app crash Context.getApplicationContext

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#452]
```
09:55:23.316 [main] ERROR com.adguard.android.commons.b - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
	at com.adguard.android.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.b.onPostExecute(Unknown Source) ~[na:0.0]
	at android.os.AsyncTask.finish(AsyncTask.java:636) ~[na:0.0]
	at android.os.AsyncTask.access$500(AsyncTask.java:177) ~[na:0.0]
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5373) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
```

**Comment by Revertron** [comment]
The fragment was detached from Activity, again.
Fixed.
