### ISSUE TITLE
Crash in HTTPS filtering settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#453]
```
10:01:19.819 [main] INFO  com.adguard.android.service.n - Retrieving HTTPs filtering configuration
10:01:20.235 [main] INFO  com.adguard.android.service.n - HTTPs filtering is disabled or CA certificate is not installed
10:01:20.238 [main] ERROR com.adguard.android.commons.b - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.adguard.filter.proxy.a.a com.adguard.filter.proxy.a.j.d()' on a null object reference
	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment$15.onClick(Unknown Source) ~[na:0.0]
	at android.view.View.performClick(View.java:4856) ~[na:0.0]
	at android.view.View$PerformClick.run(View.java:19956) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5373) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
```

One more trace (ticket ID MFI-181-54899):
```
22:46:32.025 [main] WARN  c.a.a.u.f.s.SettingsHttpsFilteringFragment - No Certificate installation activity found! Installing through browser...
22:46:32.025 [main] INFO  com.adguard.android.service.n - Retrieving HTTPs filtering configuration
22:46:32.395 [main] INFO  com.adguard.android.service.n - HTTPs filtering is disabled or CA certificate is not installed
22:46:32.408 [main] ERROR com.adguard.android.commons.b - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.adguard.filter.proxy.a.a com.adguard.filter.proxy.a.j.d()' on a null object reference
	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.c.onPostExecute(Unknown Source) ~[na:0.0]
	at android.os.AsyncTask.finish(AsyncTask.java:632) ~[na:0.0]
	at android.os.AsyncTask.access$600(AsyncTask.java:177) ~[na:0.0]
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:135) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5221) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) ~[na:0.0]
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133) ~[na:na]
```

**Comment by Revertron** [comment]
These crashes were fixed in #455
