### ISSUE TITLE
Unexpected app crash PhoneWindow$DecorView

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#454]
```
09:52:27.974 [main] ERROR com.adguard.android.commons.b - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{32091e55 V.E..... R.....ID 0,0-1056,232} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396) ~[na:0.0]
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322) ~[na:0.0]
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116) ~[na:0.0]
	at android.app.Dialog.dismissDialog(Dialog.java:349) ~[na:0.0]
	at android.app.Dialog.dismiss(Dialog.java:332) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.b.onPostExecute(Unknown Source) ~[na:0.0]
	at android.os.AsyncTask.finish(AsyncTask.java:636) ~[na:0.0]
	at android.os.AsyncTask.access$500(AsyncTask.java:177) ~[na:0.0]
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5373) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
```

**Comment by Revertron** [comment]
I think that fragment was detached from activity while AsyncTask was working, and in onPostExecute I tried to dismiss dialog attached to some phantom Activity.
Fixed.
