### ISSUE TITLE
Crash when user clicks on "Alternative certificate install" button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#455]
```
W/dalvikvm( 9806): threadid=1: thread exiting with uncaught exception (group=0x419fccf8)

W/dalvikvm( 9806): threadid=1: uncaught exception occurred

W/System.err( 9806): java.lang.NullPointerException

W/System.err( 9806): 	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment.b(Unknown Source)

W/System.err( 9806): 	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment$15.onClick(Unknown Source)

I/BufferQueue(  181): [com.adguard.android/com.adguard.android.ui.SettingsActivity](this:0xb851a348,id:818,api:1,p:9806,c:181) [release] fps:0.58, dur:8596.07, max:8531.08, min:16.10

W/System.err( 9806): 	at android.view.View.performClick(View.java:4469)

W/System.err( 9806): 	at android.view.View$PerformClick.run(View.java:18788)

W/System.err( 9806): 	at android.os.Handler.handleCallback(Handler.java:808)

W/System.err( 9806): 	at android.os.Handler.dispatchMessage(Handler.java:103)

W/System.err( 9806): 	at android.os.Looper.loop(Looper.java:193)

W/System.err( 9806): 	at android.app.ActivityThread.main(ActivityThread.java:5349)

W/System.err( 9806): 	at java.lang.reflect.Method.invokeNative(Native Method)

W/System.err( 9806): 	at java.lang.reflect.Method.invoke(Method.java:515)

W/System.err( 9806): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)

W/System.err( 9806): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)

W/System.err( 9806): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

W/System.err( 9806): 	at dalvik.system.NativeStart.main(Native Method)

W/dalvikvm( 9806): threadid=1: calling UncaughtExceptionHandler

D/OpenGLRenderer(  831): prepareDirty (0.00, 0.00, 720.00, 50.00) opaque 0 <0x63d00718>

D/OpenGLRenderer(  831): clear (0.00, 50 - 50.00 = 0.00, 720.00 - 0.00 = 720.00, 50.00 - 0.00 = 50.00) opaque 0 <0x63d00718>

D/OpenGLRenderer(  831): finish <0x63d00718>

E/com.adguard.android.commons.b( 9806): [main] Thread: Thread[main,5,main]; Uncaught exception:


E/com.adguard.android.commons.b( 9806): java.lang.NullPointerException: null

E/com.adguard.android.commons.b( 9806): 	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment.b(Unknown Source) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment$15.onClick(Unknown Source) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.view.View.performClick(View.java:4469) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.view.View$PerformClick.run(View.java:18788) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.os.Handler.handleCallback(Handler.java:808) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.os.Handler.dispatchMessage(Handler.java:103) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at android.app.ActivityThread.main(ActivityThread.java:5349) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651) ~[na:0.0]

E/com.adguard.android.commons.b( 9806): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) ~[na:na]

E/com.adguard.android.commons.b( 9806): 	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
```

And one more (looks a bit differently):
```
10:03:14.588 [main] ERROR com.adguard.android.commons.b - Thread: Thread[main,5,main]; Uncaught exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.adguard.filter.proxy.a.a com.adguard.filter.proxy.a.j.d()' on a null object reference
	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.SettingsHttpsFilteringFragment$15.onClick(Unknown Source) ~[na:0.0]
	at android.view.View.performClick(View.java:5254) ~[na:0.0]
	at android.view.View$PerformClick.run(View.java:21203) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:145) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6872) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) ~[na:0.0]
```

**Comment by Revertron** [comment]
Found & fixed!
