### ISSUE TITLE
Crash on network disconnect

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#485]
```
16:56:34.469 [pool-2-thread-1876] ERROR com.adguard.android.commons.b - Thread: Thread[pool-2-thread-1876,5,main]; Uncaught exception:

java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573) ~[na:0.0]
	at com.adguard.filter.proxy.b.close(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.n.close(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.IOUtils.closeQuietly(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.g.close(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.IOUtils.closeQuietly(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.f(Unknown Source) ~[na:0.0]
	at com.adguard.filter.c.d.close(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.IOUtils.closeQuietly(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.c(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.b(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$3.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
16:56:34.470 [pool-2-thread-1708] ERROR com.adguard.filter.proxy.a - TCP id=107411 Error while processing connection. Connection info: com.tripadvisor.tripadvisor /172.16.209.1:40440 /54.243.87.206:443 10192

java.nio.channels.ClosedChannelException: null
	at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
	at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
	at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
	at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.writeHandshakeMessage(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol$HandshakeMessage.writeToRecordStream(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsServerProtocol.sendServerHelloMessage(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.processHandshake(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.RecordStream.readRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fixed
