### ISSUE TITLE
Apps with SSL pinning

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#507]
hi. i disassembled the tinder app and searched for the keyword trustmanager. i found multiple files located in the app that have it. does that mean ssl  pinning is enabled for this app? because i see it producing errors all the time and adding endpoint exceptions

**Comment by jo2dan23** [comment]
if someone could take a look at the app that would be great. here is playstore link: https://play.google.com/store/apps/details?id=com.tinder&hl=en

**Comment by jo2dan23** [comment]
ive seen it in two more apps. but i don't think it is enabled in them. how do i tell if it is enabled?

**Comment by ameshkov** [comment]
> does that mean ssl pinning is enabled for this app?

Yep, seems so.

> how do i tell if it is enabled?

Look for "unknown_ca" errors in Adguard log, usually (but not always) client app sends this alert when ssl pinning is in use.

**Comment by jo2dan23** [comment]
I cant seem to find that. How did you tell that snapchat had ssl pinning?

**Comment by jo2dan23** [comment]
See screenshot: http://imgur.com/CutEbFX

**Comment by jo2dan23** [comment]
Looks like the apps,below all,have ssl pinning.

https://play.google.com/store/apps/details?id=mobi.ifunny

https://play.google.com/store/apps/details?id=com.tozelabs.tvshowtime

https://play.google.com/store/apps/details?id=com.tumblr

Screenshots,of,files with x509:

http://i.imgur.com/6GV4zHN.png
http://i.imgur.com/KYZ1kM8.png
http://i.imgur.com/lUW61Bs.png

**Comment by jo2dan23** [comment]
i keep finding more and more with x509 in the files. should i keep adding them to the list?

**Comment by ameshkov** [comment]
It could be just a part of the library they all use (like okhttp).

It does not necessary means that these apps actually use ssl pinning.

**Comment by jo2dan23** [comment]
how do we tell if they do then?

**Comment by ameshkov** [comment]
Yeah, that's it, part of okhttp:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/CertificatePinner.java

**Comment by ameshkov** [comment]
> how do we tell if they do then?

As I've said, look for SSL handshake errors in AG log.

You should see something like that there:
"Adding endpoint XXXXX to exceptions"

But again, that's not always means ssl pinning.
Check if you see this error **every time** when you run the app (restart AG and clean app cache before running it second time).

**Comment by jo2dan23** [comment]
`15:23:34.143 [pool-3-thread-513] ERROR com.adguard.filter.proxy.a - TCP id=101431 Error while processing connection. Connection info: com.tumblr /172.16.209.1:38051 /52.84.2.128:443 10091

java.nio.channels.ClosedChannelException: null
at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.writeHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol$HandshakeMessage.writeToRecordStream(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.sendServerKeyExchangeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.readRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
15:23:34.149 [pool-3-thread-521] ERROR com.adguard.filter.proxy.a - TCP id=101433 Error while processing connection. Connection info: com.tumblr /172.16.209.1:38407 /93.184.216.185:443 10091

java.nio.channels.ClosedChannelException: null
at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.writeHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol$HandshakeMessage.writeToRecordStream(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.sendServerKeyExchangeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.readRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
15:23:34.158 [pool-3-thread-528] ERROR com.adguard.filter.proxy.a - TCP id=101434 Error while processing connection. Connection info: com.tumblr /172.16.209.1:49616 /209.197.3.20:443 10091

java.io.IOException: Internal TLS error, this could be an attack
at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
15:23:34.161 [pool-3-thread-529] ERROR com.adguard.filter.proxy.a - TCP id=101432 Error while processing connection. Connection info: com.tumblr /172.16.209.1:47886 /209.197.3.20:443 10091

java.nio.channels.ClosedChannelException: null
at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.writeHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol$HandshakeMessage.writeToRecordStream(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.sendServerKeyExchangeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.readRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
15:23:34.712 [pool-3-thread-521] ERROR com.adguard.filter.proxy.a - TCP id=101436 Error while processing connection. Connection info: com.tumblr /:::44985 /209.197.3.20:443 10091

java.nio.channels.ClosedChannelException: null
at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418) ~[na:0.0]
at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol.writeHandshakeMessage(Unknown Source) ~[na:0.0]
at org.bouncycastle.crypto.tls.TlsProtocol$Handsh`


this is the error i get on every start of tumblr app

**Comment by jo2dan23** [comment]
it looks like adding these to https whitelist got rid of the important errors. i think the other ones are for ads

api.tumblr.com
media.tumblr.com

**Comment by jo2dan23** [comment]
adding cdninstagram.com to https whitelist fixes errors in tinder app

**Comment by jo2dan23** [comment]
what does cannot read http request internal tls error mean?

**Comment by jo2dan23** [comment]
adding gotinder.com and cdninstagram.com to https whitelist stops errors in tinder app

**Comment by jo2dan23** [comment]
am closing this and making a thread for the correct app
