### ISSUE TITLE
Adguard stopped with error No definition found for class:'com.adguard.android.service.protectionstate.a'

### ISSUE THREAD

**Issue by lansman** [AdguardTeam/AdguardForAndroid#5262]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

- OS version: Android MIUI 14.0.3
- Device: Redmi Note 10S (global)

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Russian filter

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. I unlocked my phone once and noticed Adguard had stopped and MIUI error notification appeared

Problem occured once. I rebooted the phone and problem gone. But maybe you want to know, just for the case.

### Expected Behavior

Adguard doesn't stop, no error appears

### Actual Behavior

An error appeared

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_2024-03-13-16-57-34-220_com miui bugreport](https://github.com/AdguardTeam/AdguardForAndroid/assets/1588720/24204643-ba6e-460b-871e-6f7f403f72bc)

</details>

### Additional Information

java.lang.RuntimeException: Unable to start service com.adguard.android.service.protectionstate.ProtectionStateForegroundService@526b658 with Intent { act=Start protection [cmp=com.adguard.android/.service.protectionstate.ProtectionStateForegroundService](http://cmp=com.adguard.android/.service.protectionstate.ProtectionStateForegroundService) }: ah.e: |- No definition found for class:'com.adguard.android.service.protectionstate.a'. Check your definitions!
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4914)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: ah.e: |- No definition found for class:'com.adguard.android.service.protectionstate.a'. Check your definitions!
	at hh.a.q(Scope.kt:63)
	at hh.a.p(Scope.kt:116)
	at hh.a.o(Scope.kt:45)
	at hh.a.b(Scope.kt:1)
	at hh.a$b.invoke(Scope.kt:9)
	at ih.a.c(Measure.kt:7)
	at ih.a.b(Measure.kt:6)
	at hh.a.g(Scope.kt:89)
	at com.adguard.android.service.protectionstate.ProtectionStateForegroundService$n.invoke(ComponentCallbackExt.kt:17)
	at sb.r.getValue(LazyJVM.kt:21)
	at com.adguard.android.service.protectionstate.ProtectionStateForegroundService.l(ProtectionStateForegroundService.kt:3)
	at com.adguard.android.service.protectionstate.ProtectionStateForegroundService.onStartCommand(ProtectionStateForegroundService.kt:1)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4896)
	... 9 more

**Comment by maxikuzmin** [comment]
@lansman thank you, we will look into what happened. 
Have you had this happen again?

**Comment by maxikuzmin** [comment]
@lansman it would be nice to understand the steps to reproduce the problem

**Comment by lansman** [comment]
@maxikuzmin no, never

**Comment by lansman** [comment]
> @lansman thank you, we will look into what happened. Have you had this happen again?
No, never

> @lansman it would be nice to understand the steps to reproduce the problem
I don't know how to reproduce, it happened by its own

**Comment by maxikuzmin** [comment]
@lansman to solve the problem, we need to figure out how to reproduce the problem.
Could you please clarify the steps to reproduce this error?

**Comment by maxikuzmin** [comment]
@lansman without steps to repeat the issue, it's hard to figure out how to fix it. We need to understand how to reproduce the issue to fix it
I will close this Issue for the time being. 
Please, if in the future the problem occurs again after certain steps, please reopen the issue
