### ISSUE TITLE
Crash on Kindle when we try to start VPN shortly after device boot

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#7]
Linked forum thread:
http://forum.adguard.com/showthread.php?6557-Reverting-back-to-main-screen&p=58450#post58450

Errors:
    17:29:05.623 [main] INFO com.adguard.android.ui.MainActivity - Start preparing protection
    17:29:05.632 [main] ERROR com.adguard.android.ui.MainActivity - Error while preparing vpn, prepare() not ready

    17:29:05.634 [main] ERROR c.a.a.c.CustomExceptionHandler - Thread:main;Uncaught exception:
    android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0033 type #0x1d is not valid

What should we do:
1. Fix that crash
2. If device is Kindle we should tell user that device is not yet ready and he should wait some time

**Comment by Revertron** [comment]
Full trace:

android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0033 type #0x1d is not valid
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2431) ~[na:0.0]
	at android.content.res.Resources.getLayout(Resources.java:946) ~[na:0.0]
	at android.view.LayoutInflater.inflate(LayoutInflater.java:395) ~[na:0.0]
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353) ~[na:0.0]
	at android.widget.Toast.makeText(Toast.java:257) ~[na:0.0]
	at android.widget.Toast.makeText(Toast.java:282) ~[na:0.0]
	at com.adguard.android.ui.fragment.settings.SettingsGeneralFragment$2.onClick(Unknown Source) ~[na:0.0]
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(Unknown Source) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:145) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5266) ~[na:0.0]
	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) ~[na:0.0]
	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]

The problem is in Toast. The Toast was revised in #4
