### ISSUE TITLE
Add support for the :style pseudo class syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#701]
Based on:
https://github.com/AdguardTeam/AdguardFilters/issues/2571

Also we should add CSS pseudo classes validation.

**Comment by ameshkov** [comment]
Done

**Comment by ameshkov** [comment]
```
17:18:00.004 [pool-4-thread-2] WARN  com.adguard.filter.rules.FilterRule - Error creating filter rule ##a[href^="http://www.FriendlyDuck.com/AF_"]:
{}
java.lang.IllegalArgumentException: Unknown pseudo class: a[href^="http://www.FriendlyDuck.com/AF_"]
	at com.adguard.filter.rules.CssFilterRule.<init>(CssFilterRule.java:107) ~[na:0.0]
	at com.adguard.filter.rules.FilterRule.createRule(FilterRule.java:104) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRule(RequestFilter.java:80) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRules(RequestFilter.java:96) ~[na:0.0]
	at com.adguard.android.filtering.filter.HttpFilter.initialize(HttpFilter.java:118) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.initializeHttpFilter(ProtectionServiceImpl.java:286) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.configureHttpFilter(ProtectionServiceImpl.java:303) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.access$400(ProtectionServiceImpl.java:35) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl$StartVpnServiceTask.processTask(ProtectionServiceImpl.java:320) ~[na:0.0]
	at com.adguard.android.service.LongRunningTask.execute(LongRunningTask.java:46) ~[na:0.0]
	at com.adguard.commons.concurrent.DispatcherThreadPool$DispatcherTaskRunner.run(DispatcherThreadPool.java:206) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
```
18:09:48.782 [pool-4-thread-1] WARN  com.adguard.filter.rules.FilterRule - Error creating filter rule msn.com##.todaystripe::after:

java.lang.StringIndexOutOfBoundsException: length=1; index=1
	at java.lang.String.charAt(Native Method) ~[na:0.0]
	at com.adguard.filter.rules.CssFilterRule.parsePseudoClass(CssFilterRule.java:169) ~[na:0.0]
	at com.adguard.filter.rules.CssFilterRule.<init>(CssFilterRule.java:102) ~[na:0.0]
	at com.adguard.filter.rules.FilterRule.createRule(FilterRule.java:104) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRule(RequestFilter.java:80) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRules(RequestFilter.java:96) ~[na:0.0]
	at com.adguard.android.filtering.filter.HttpFilter.initialize(HttpFilter.java:118) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.initializeHttpFilter(ProtectionServiceImpl.java:286) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.configureHttpFilter(ProtectionServiceImpl.java:303) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.access$400(ProtectionServiceImpl.java:35) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl$StartVpnServiceTask.processTask(ProtectionServiceImpl.java:320) ~[na:0.0]
	at com.adguard.android.service.LongRunningTask.execute(LongRunningTask.java:46) ~[na:0.0]
	at com.adguard.commons.concurrent.DispatcherThreadPool$DispatcherTaskRunner.run(DispatcherThreadPool.java:206) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
18:09:48.827 [pool-4-thread-1] WARN  com.adguard.filter.rules.FilterRule - Error creating filter rule ###Meebo\:AdElement\.Root:

java.lang.IllegalArgumentException: Unknown pseudo class: #Meebo\:AdElement\.Root
	at com.adguard.filter.rules.CssFilterRule.<init>(CssFilterRule.java:108) ~[na:0.0]
	at com.adguard.filter.rules.FilterRule.createRule(FilterRule.java:104) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRule(RequestFilter.java:80) ~[na:0.0]
	at com.adguard.filter.filters.RequestFilter.addRules(RequestFilter.java:96) ~[na:0.0]
	at com.adguard.android.filtering.filter.HttpFilter.initialize(HttpFilter.java:118) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.initializeHttpFilter(ProtectionServiceImpl.java:286) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.configureHttpFilter(ProtectionServiceImpl.java:303) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl.access$400(ProtectionServiceImpl.java:35) ~[na:0.0]
	at com.adguard.android.service.ProtectionServiceImpl$StartVpnServiceTask.processTask(ProtectionServiceImpl.java:320) ~[na:0.0]
	at com.adguard.android.service.LongRunningTask.execute(LongRunningTask.java:46) ~[na:0.0]
	at com.adguard.commons.concurrent.DispatcherThreadPool$DispatcherTaskRunner.run(DispatcherThreadPool.java:206) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Fixed
