### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#719]
id 1310380, full log is available

Nexus 5x
local vpn

"I randomly get an error that says "unfortunately Adguard has stopped."
This happens when opening certain apps, usually Chrome. For example,
if I tap on an article in my Google Now stream. It has also happened
when opening Netflix, even though I don't have Adguard enabled on that
app."

Uncaught exception from the latest log:
https://gist.github.com/vozersky/b5eefdd9978d06f582835702714ea5be

**Comment by vozersky** [comment]
"It happened again, twice in a row and my phone wasn't even idle. The first
time it happened I was opening up Facebook mobile in Chrome. The second
time I was teaching a package from Gmail"


From the latest log:

"13:33:15.155 [pool-2-thread-40] ERROR com.adguard.android.commons.c - Thread: Thread[pool-2-thread-40,5,main]; Uncaught exception:

java.lang.NullPointerException: rhs == null
	at java.lang.String.compareTo(Native Method) ~[na:0.0]
	at java.lang.String.compareTo(String.java:335) ~[na:0.0]
	at java.util.Arrays.binarySearch(Arrays.java:524) ~[na:0.0]
	at java.util.Arrays.binarySearch(Arrays.java:494) ~[na:0.0]
	at com.adguard.android.filtering.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.b.d(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.b.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.m.c(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.a$1.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]

**Comment by Revertron** [comment]
We refactored the fix once more time, need to test.

**Comment by Revertron** [comment]
I suppose there is no bug in current beta. Closing as fixed.
