### ISSUE TITLE
ENOBUFS error while writing to the TUN

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#724]
Discussion:
https://forum.adguard.com/index.php?threads/android-2-7-153-connection-issues-thanks-to-adguard.12197/

```
18:55:32.642 [Thread-33033] ERROR com.adguard.android.filtering.vpn.e - TUN: Error while writing to the tun device
java.io.IOException: write failed: ENOBUFS (No buffer space available)
    at libcore.io.IoBridge.write(IoBridge.java:498) ~[na:0.0]
    at java.io.FileOutputStream.write(FileOutputStream.java:186) ~[na:0.0]
    at com.adguard.commons.b.d.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.packet.b.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.e.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.a.b(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.m$1.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.lwip.c.f(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.lwip.c.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.n.write(Unknown Source) ~[na:0.0]
    at com.adguard.commons.b.d.a(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.b.a(Unknown Source) ~[na:0.0]
    at com.adguard.commons.b.s.a(Unknown Source) ~[na:0.0]
    at com.adguard.commons.b.s$1.run(Unknown Source) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: android.system.ErrnoException: write failed: ENOBUFS (No buffer space available)
    at libcore.io.Posix.writeBytes(Native Method) ~[na:0.0]
    at libcore.io.Posix.write(Posix.java:271) ~[na:0.0]
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313) ~[na:0.0]
    at libcore.io.IoBridge.write(IoBridge.java:493) ~[na:0.0]
    ... 14 common frames omitted
```

**Comment by ameshkov** [comment]
Unanswered question about it on SO:
http://stackoverflow.com/questions/23623035/android-vpnservice-write-packet-error-no-buffer-space-available

**Comment by ameshkov** [comment]
Relevant questions:
http://stackoverflow.com/questions/1043567/java-ioexception-no-buffer-space-available-while-sending-udp-packets-on-linux

**Comment by ameshkov** [comment]
AG now handles ENOBUFS error

**Comment by 739988940** [comment]
have you solve this problem？

**Comment by sfionov** [comment]
This issue is about old TCP/IP stack implementation which was replaced in AdGuard 2.10.
New one uses asynchronous I/O where buffers exhaustion is already handled.
