### ISSUE TITLE
NullPointerException in AppRulesService

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#727]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.adguard.android.filtering.filter.AppRules.isMobileData()' on a null object reference
            at com.adguard.android.service.AppRulesServiceImpl.allowDnsRequests(AppRulesServiceImpl.java:131)
            at com.adguard.android.service.AppRulesServiceImpl.save(AppRulesServiceImpl.java:113)
            at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.onMainCheckBoxChanged(FirewallPackageFragment.java:154)
            at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.access$200(FirewallPackageFragment.java:44)
            at com.adguard.android.ui.fragment.settings.FirewallPackageFragment$2.onCheckedChanged(FirewallPackageFragment.java:114)
            at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
            at com.adguard.android.ui.fragment.settings.FirewallPackageFragment.onViewCreated(FirewallPackageFragment.java:117)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by Revertron** [comment]
Fixed!
