### ISSUE TITLE
HTTPS sites do not open in Chrome Dev 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#793]
с новым (55.0.2860.0) [chrome dev](https://play.google.com/store/apps/details?id=com.chrome.dev&hl=uk) не работает фильтрация https с ошибкой ssl conn error

**Comment by ameshkov** [comment]
I can confirm the issue, thank you for alerting us!

**Comment by Bluscream** [comment]
I can't read russian but i think i have the same error.

**Comment by Bluscream** [comment]
Its already in Chrome Beta https://gyazo.com/402de7a0c10bfe0696dfcbe8ddcde575

**Comment by Bluscream** [comment]
@ameshkov !

**Comment by kudiaborm** [comment]
I also receive this error. Multiple errors get returned by chromedev. 

`09-22 10:31:17.063 20408-20482/? E/chromium: [ERROR:ssl_client_socket_impl.cc(1173)] handshake failed; returned -1, SSL error code 1, net_error -107
09-22 10:31:17.064 20408-20482/? E/chromium: [ERROR:ssl_client_socket_impl.cc(1173)] handshake failed; returned -1, SSL error code 1, net_error -107
09-22 10:31:17.066 10462-18752/? E/com.adguard.filter.proxy.a: [pool-2-thread-99] TCP id=100428 Error while processing connection. Connection info: com.chrome.dev /172.16.209.1:37471 /151.101.4.67:443 10156
                                                               java.io.IOException: Internal TLS error, this could be an attack
                                                               	at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
                                                               	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
                                                               	at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
                                                               	at org.bouncycastle.crypto.tls.TlsServerProtocol.accept(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.ssl.k.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.ssl.k.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.android.filtering.filter.i.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.n.a(Unknown Source) ~[na:0.0]
                                                               	at com.adguard.filter.proxy.n$2.run(Unknown Source) ~[na:0.0]
                                                               	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
                                                               	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
                                                               	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]`


Full log attached
Some links worked. One didn't reloading the page allows it to load but it fails on the first try.
[SSL_Error.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/487946/SSL_Error.txt)

**Comment by kudiaborm** [comment]
I'd also like to mention  this is probably an issue with QUIC and UDP as it's having issues decrypting and blocking ads over port 443.
I recently had issues with this on my work network as evidenced by this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=638945

Resources:
[https://www.chromium.org/quic](QUIC Blog)
[https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/ksokVdwXfQ0)](What blocks QUIC on a network)
[(https://ma.ttias.be/googles-quic-protocol-moving-web-tcp-udp/](Other Info)

**Comment by ameshkov** [comment]
@kudiaborm it seems that you were right about QUIC thing. The issue seems to be gone after #766 was fixed. Although, I have no clue what's the link between these two issues.

**Comment by kudiaborm** [comment]
Recently google seems to have been adding people to QUIC experiments, there is also a flag to use QUIC by default. Perhaps HTTPS is transitioning to UDP/QUIC (:80 and :443) and thus this issue. 
If there is any transparency on the issue of love to know what was causing it

**Comment by ameshkov** [comment]
I just don't really understand how it could mess with other websites (QUIC is used by google websites only).
