### ISSUE TITLE
UDP: Error while processing vpn data

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#840]
Getting an error:

```
UDP id=689 Error while processing vpn data
                                                                          java.io.IOException: Operation not permitted
                                                                            at sun.nio.ch.DatagramDispatcher.write0(Native Method) ~[na:0.0]
                                                                            at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:52) ~[na:0.0]
                                                                            at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:0.0]
                                                                            at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:0.0]
                                                                            at sun.nio.ch.DatagramChannelImpl.write(DatagramChannelImpl.java:622) ~[na:0.0]
                                                                            at com.adguard.commons.b.j.write(Unknown Source) ~[na:0.0]
                                                                            at com.adguard.android.filtering.vpn.a.a(Unknown Source) ~[na:0.0]
                                                                            at com.adguard.android.filtering.vpn.p.c(Unknown Source) ~[na:0.0]
                                                                            at com.adguard.android.filtering.vpn.a$1.run(Unknown Source) ~[na:0.0]
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
                                                                            at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

**Comment by ameshkov** [comment]
Quoting https://github.com/netty/netty/issues/1258#issuecomment-16289662
> The discussion at http://www.archivum.info/comp.protocols.tcp-ip/2009-05/00088/UDP-socket-amp-amp-sendto-amp-amp-EPERM.html seems to indicate that this is "normal" behavior of the Linux kernel if a UDP socket is sending too fast to one (or more?) hosts.

The same discussion on google groups:
https://groups.google.com/forum/#!topic/comp.protocols.tcp-ip/Qou9Sfgr77E

Relevant quote:
> > What may be the cause of my problem?
> Failure to implement transmit pacing. With UDP, you are responsible
> for spacing out your sends at a rational rate. You should start out at
> a very slow rate and raise the rate as you confirm that there is
> minimal or no packet loss. You can simply ignore this error if you
> want, assuming you do properly implement transmit pacing.

**Comment by ameshkov** [comment]
Fixed

**Comment by Revertron** [comment]
May be we need to catch IOException, not just Exception?

**Comment by ameshkov** [comment]
Ah, i suppose catching all exceptions is good enough:)
