### ISSUE TITLE
Cannot parse HTML filtering rule with wildcard attribute

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#917]
```
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426): [pool-2-thread-12] Error creating filter rule indiatimes.com$$script[wildcard="*var _0x*false;if(!_0x*}(document,window));*"][max-length="8000"]:
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426): java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 29
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426): ^.*var _0x.*false;if\(!_0x.*}\(document,window\)\);.*$
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):                              ^
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at java.util.regex.Pattern.compileImpl(Native Method) ~[na:0.0]
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at java.util.regex.Pattern.compile(Pattern.java:1340) ~[na:0.0]
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at java.util.regex.Pattern.<init>(Pattern.java:1324) ~[na:0.0]
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at java.util.regex.Pattern.compile(Pattern.java:971) ~[na:0.0]
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at com.adguard.commons.c.d.<init>(Unknown Source) ~[na:0.0]
11-21 08:28:45.430 W/com.adguard.filter.rules.h(2426):     at com.adguard.filter.rules.b.<init>(Unknown Source) ~[na:0.0]
```

**Comment by nkartyshov** [comment]
fixed
