### ISSUE TITLE
Error while applying app update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#954]
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.adguard.android (has extras) } in com.adguard.android.service.am@16b7143
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:893) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5441) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) ~[na:0.0]
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) ~[na:na]
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.provider.DownloadProvider uri content://downloads/all_downloads/175 from pid=18423, uid=10095 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620) ~[na:0.0]
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183) ~[na:0.0]
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146) ~[na:0.0]
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692) ~[na:0.0]
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1121) ~[na:0.0]
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:957) ~[na:0.0]
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:810) ~[na:0.0]
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:764) ~[na:0.0]
	at android.app.DownloadManager.openDownloadedFile(DownloadManager.java:1454) ~[na:0.0]
	at com.adguard.android.service.am.onReceive(Unknown Source) ~[na:0.0]
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:883) ~[na:0.0]
	... 8 common frames omitted
```

**Comment by nkartyshov** [comment]
fixed
