### ISSUE TITLE
Cannot receive and send MMS

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#974]
id1457490

device Galaxy S7

STR:

 1. Download App. in Home page (https://adguard.com/en/adguard-android/install.html#howToInstall)
 2. copy app to phone
 3. install and execute the app.
 4. send and receive message

```
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService: [Thread-6] Interrupted system call:\r
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService: java.io.InterruptedIOException: Error Interrupted system call occurred while polling file descriptor 69
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at com.adguard.android.filtering.commons.NativeUtils.readFd(Native Method) ~[na:0.0]
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at com.adguard.android.filtering.vpn.e.b(Unknown Source) ~[na:0.0]
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at com.adguard.android.filtering.vpn.FilteringVpnService.g(Unknown Source) ~[na:0.0]
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at com.adguard.android.filtering.vpn.FilteringVpnService.a(Unknown Source) ~[na:0.0]
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
11-12 03:11:45.438  8500 10059 W com.adguard.android.filtering.vpn.FilteringVpnService:    at java.lang.Thread.run(Thread.java:761) ~[na:0.0] 
```

**Comment by vozersky** [comment]
requested more details

**Comment by ameshkov** [comment]
@vozersky any update on this?

**Comment by vozersky** [comment]
No updates. We can close it, I guess.

**Comment by ameshkov** [comment]
@vozersky don't forget to add a proper label and remove the milestone for this sort of issues.
